// Generated by tools/genref.java --jar <client.jar> --opaquecube.
// Do not edit by hand.
//
// `Block.opaqueCubeLookup`, straight out of a loaded jar. This is the array
// world generation reads -- BlockMushroom's ground test is a lookup into it --
// and it is filled in the Block constructor, before any graphics setting is
// applied. `live` is what isOpaqueCube() answers right now, for comparison:
// they differ only for leaves, and only because the video options default to
// fancy. See docs/worldgen-a1.1.2.md.
//
// Regenerate with:
//   java tools/genref.java --jar <client.jar> --opaquecube
//     redirected to tests/opaque_cube_vectors.hpp

#pragma once

#include "core/util/types.hpp"

namespace mc::test {

struct OpaqueCubeEntry {
    bool cached;   // Block.opaqueCubeLookup[id]
    bool live;     // isOpaqueCube() as the class stands now
    bool defined;  // whether this version constructs the block at all
};

inline constexpr OpaqueCubeEntry kOpaqueCube[256] = {
    {false, false, false},   // 0
    {true, true, true},   // 1
    {true, true, true},   // 2
    {true, true, true},   // 3
    {true, true, true},   // 4
    {true, true, true},   // 5
    {false, false, true},   // 6
    {true, true, true},   // 7
    {false, false, true},   // 8
    {false, false, true},   // 9
    {false, false, true},   // 10
    {false, false, true},   // 11
    {true, true, true},   // 12
    {true, true, true},   // 13
    {true, true, true},   // 14
    {true, true, true},   // 15
    {true, true, true},   // 16
    {true, true, true},   // 17
    {true, true, true},   // 18
    {true, true, true},   // 19
    {false, false, true},   // 20
    {false, false, false},   // 21
    {false, false, false},   // 22
    {false, false, false},   // 23
    {false, false, false},   // 24
    {false, false, false},   // 25
    {false, false, false},   // 26
    {false, false, false},   // 27
    {false, false, false},   // 28
    {false, false, false},   // 29
    {false, false, false},   // 30
    {false, false, false},   // 31
    {false, false, false},   // 32
    {false, false, false},   // 33
    {false, false, false},   // 34
    {true, true, true},   // 35
    {false, false, false},   // 36
    {false, false, true},   // 37
    {false, false, true},   // 38
    {false, false, true},   // 39
    {false, false, true},   // 40
    {true, true, true},   // 41
    {true, true, true},   // 42
    {false, true, true},   // 43
    {false, false, true},   // 44
    {true, true, true},   // 45
    {true, true, true},   // 46
    {true, true, true},   // 47
    {true, true, true},   // 48
    {true, true, true},   // 49
    {false, false, true},   // 50
    {false, false, true},   // 51
    {false, false, true},   // 52
    {false, false, true},   // 53
    {true, true, true},   // 54
    {false, false, true},   // 55
    {true, true, true},   // 56
    {true, true, true},   // 57
    {true, true, true},   // 58
    {false, false, true},   // 59
    {false, false, true},   // 60
    {true, true, true},   // 61
    {true, true, true},   // 62
    {false, false, true},   // 63
    {false, false, true},   // 64
    {false, false, true},   // 65
    {false, false, true},   // 66
    {false, false, true},   // 67
    {false, false, true},   // 68
    {false, false, true},   // 69
    {false, false, true},   // 70
    {false, false, true},   // 71
    {false, false, true},   // 72
    {true, true, true},   // 73
    {true, true, true},   // 74
    {false, false, true},   // 75
    {false, false, true},   // 76
    {false, false, true},   // 77
    {false, false, true},   // 78
    {false, false, true},   // 79
    {true, true, true},   // 80
    {false, false, true},   // 81
    {true, true, true},   // 82
    {false, false, true},   // 83
    {true, true, true},   // 84
    {false, false, true},   // 85
    {false, false, false},   // 86
    {false, false, false},   // 87
    {false, false, false},   // 88
    {false, false, false},   // 89
    {false, false, false},   // 90
    {false, false, false},   // 91
    {false, false, false},   // 92
    {false, false, false},   // 93
    {false, false, false},   // 94
    {false, false, false},   // 95
    {false, false, false},   // 96
    {false, false, false},   // 97
    {false, false, false},   // 98
    {false, false, false},   // 99
    {false, false, false},   // 100
    {false, false, false},   // 101
    {false, false, false},   // 102
    {false, false, false},   // 103
    {false, false, false},   // 104
    {false, false, false},   // 105
    {false, false, false},   // 106
    {false, false, false},   // 107
    {false, false, false},   // 108
    {false, false, false},   // 109
    {false, false, false},   // 110
    {false, false, false},   // 111
    {false, false, false},   // 112
    {false, false, false},   // 113
    {false, false, false},   // 114
    {false, false, false},   // 115
    {false, false, false},   // 116
    {false, false, false},   // 117
    {false, false, false},   // 118
    {false, false, false},   // 119
    {false, false, false},   // 120
    {false, false, false},   // 121
    {false, false, false},   // 122
    {false, false, false},   // 123
    {false, false, false},   // 124
    {false, false, false},   // 125
    {false, false, false},   // 126
    {false, false, false},   // 127
    {false, false, false},   // 128
    {false, false, false},   // 129
    {false, false, false},   // 130
    {false, false, false},   // 131
    {false, false, false},   // 132
    {false, false, false},   // 133
    {false, false, false},   // 134
    {false, false, false},   // 135
    {false, false, false},   // 136
    {false, false, false},   // 137
    {false, false, false},   // 138
    {false, false, false},   // 139
    {false, false, false},   // 140
    {false, false, false},   // 141
    {false, false, false},   // 142
    {false, false, false},   // 143
    {false, false, false},   // 144
    {false, false, false},   // 145
    {false, false, false},   // 146
    {false, false, false},   // 147
    {false, false, false},   // 148
    {false, false, false},   // 149
    {false, false, false},   // 150
    {false, false, false},   // 151
    {false, false, false},   // 152
    {false, false, false},   // 153
    {false, false, false},   // 154
    {false, false, false},   // 155
    {false, false, false},   // 156
    {false, false, false},   // 157
    {false, false, false},   // 158
    {false, false, false},   // 159
    {false, false, false},   // 160
    {false, false, false},   // 161
    {false, false, false},   // 162
    {false, false, false},   // 163
    {false, false, false},   // 164
    {false, false, false},   // 165
    {false, false, false},   // 166
    {false, false, false},   // 167
    {false, false, false},   // 168
    {false, false, false},   // 169
    {false, false, false},   // 170
    {false, false, false},   // 171
    {false, false, false},   // 172
    {false, false, false},   // 173
    {false, false, false},   // 174
    {false, false, false},   // 175
    {false, false, false},   // 176
    {false, false, false},   // 177
    {false, false, false},   // 178
    {false, false, false},   // 179
    {false, false, false},   // 180
    {false, false, false},   // 181
    {false, false, false},   // 182
    {false, false, false},   // 183
    {false, false, false},   // 184
    {false, false, false},   // 185
    {false, false, false},   // 186
    {false, false, false},   // 187
    {false, false, false},   // 188
    {false, false, false},   // 189
    {false, false, false},   // 190
    {false, false, false},   // 191
    {false, false, false},   // 192
    {false, false, false},   // 193
    {false, false, false},   // 194
    {false, false, false},   // 195
    {false, false, false},   // 196
    {false, false, false},   // 197
    {false, false, false},   // 198
    {false, false, false},   // 199
    {false, false, false},   // 200
    {false, false, false},   // 201
    {false, false, false},   // 202
    {false, false, false},   // 203
    {false, false, false},   // 204
    {false, false, false},   // 205
    {false, false, false},   // 206
    {false, false, false},   // 207
    {false, false, false},   // 208
    {false, false, false},   // 209
    {false, false, false},   // 210
    {false, false, false},   // 211
    {false, false, false},   // 212
    {false, false, false},   // 213
    {false, false, false},   // 214
    {false, false, false},   // 215
    {false, false, false},   // 216
    {false, false, false},   // 217
    {false, false, false},   // 218
    {false, false, false},   // 219
    {false, false, false},   // 220
    {false, false, false},   // 221
    {false, false, false},   // 222
    {false, false, false},   // 223
    {false, false, false},   // 224
    {false, false, false},   // 225
    {false, false, false},   // 226
    {false, false, false},   // 227
    {false, false, false},   // 228
    {false, false, false},   // 229
    {false, false, false},   // 230
    {false, false, false},   // 231
    {false, false, false},   // 232
    {false, false, false},   // 233
    {false, false, false},   // 234
    {false, false, false},   // 235
    {false, false, false},   // 236
    {false, false, false},   // 237
    {false, false, false},   // 238
    {false, false, false},   // 239
    {false, false, false},   // 240
    {false, false, false},   // 241
    {false, false, false},   // 242
    {false, false, false},   // 243
    {false, false, false},   // 244
    {false, false, false},   // 245
    {false, false, false},   // 246
    {false, false, false},   // 247
    {false, false, false},   // 248
    {false, false, false},   // 249
    {false, false, false},   // 250
    {false, false, false},   // 251
    {false, false, false},   // 252
    {false, false, false},   // 253
    {false, false, false},   // 254
    {false, false, false},   // 255
};

}  // namespace mc::test
