// Generated by tools/genref.java --jar <client.jar> --plant <scratch-dir>.
// Do not edit by hand.
//
// WorldGenReed (`es`) and WorldGenCactus (`da`) against a **real a1.1.2 World**
// on a procedurally built scene -- see tools/genref.java for the four scenes,
// which tests/plant_test.cpp has to build identically.
//
// `afterDraw` is a stream fingerprint: the next long drawn once the generator
// has finished. It matches only if the same number of random numbers were
// consumed, which is the failure this pair is most likely to have.
//
// Regenerate with:
//   java tools/genref.java --jar <client.jar> --plant /tmp/genref-scratch
//     redirected to tests/plant_vectors.hpp

#pragma once

#include "core/util/types.hpp"

namespace mc::test {

inline constexpr int kPlantBox = 12;
inline constexpr int kPlantGroundTop = 40;
inline constexpr int kPlantGroundDepth = 4;
inline constexpr int kPlantHeadroom = 8;

// The still-water pool in kSceneGrassWater, as offsets from the case origin.
inline constexpr int kWaterX0 = -3;
inline constexpr int kWaterX1 = 3;
inline constexpr int kWaterZ0 = 2;
inline constexpr int kWaterZ1 = 3;

enum PlantScene {
    kSceneSand = 0,
    kSceneGrass = 1,
    kSceneGrassWater = 2,
    kSceneSandScatter = 3,
};

// Offsets from the case's origin in x and z; y is absolute.
struct PlantPlacement {
    i32 dx;
    i32 y;
    i32 dz;
};

struct PlantCase {
    int kind;         // 0 = reed, 1 = cactus
    int scene;
    i64 rngSeed;
    i32 x;
    i32 y;
    i32 z;
    i64 afterDraw;    // stream fingerprint
    int placementCount;
    const PlantPlacement* placements;
};

inline constexpr PlantPlacement kPlant0[5] = {
    {0, 41, 1},
    {0, 42, 1},
    {0, 43, 1},
    {1, 41, 1},
    {1, 42, 1},
};
inline constexpr PlantPlacement kPlant1[9] = {
    {-2, 41, 1},
    {-2, 42, 1},
    {-2, 43, 1},
    {-1, 41, 1},
    {-1, 42, 1},
    {-1, 43, 1},
    {-1, 44, 1},
    {2, 41, 1},
    {2, 42, 1},
};
inline constexpr PlantPlacement kPlant2[4] = {
    {1, 41, 1},
    {1, 42, 1},
    {2, 41, 1},
    {2, 42, 1},
};
inline constexpr PlantPlacement kPlant3[1] = {
    {0, 0, 0},
};
inline constexpr PlantPlacement kPlant4[1] = {
    {0, 0, 0},
};
inline constexpr PlantPlacement kPlant5[1] = {
    {0, 0, 0},
};
inline constexpr PlantPlacement kPlant6[4] = {
    {-6, 41, -1},
    {-1, 41, 1},
    {6, 41, -1},
    {6, 42, -1},
};
inline constexpr PlantPlacement kPlant7[3] = {
    {-7, 41, 7},
    {3, 41, -2},
    {3, 41, 2},
};
inline constexpr PlantPlacement kPlant8[5] = {
    {0, 41, 5},
    {1, 41, -4},
    {5, 41, -6},
    {5, 42, -6},
    {5, 43, -6},
};
inline constexpr PlantPlacement kPlant9[1] = {
    {0, 0, 0},
};
inline constexpr PlantPlacement kPlant10[1] = {
    {0, 0, 0},
};
inline constexpr PlantPlacement kPlant11[1] = {
    {0, 0, 0},
};

inline constexpr int kPlantCaseCount = 12;

// Total blocks placed across every case. A fixture that placed nothing would
// be satisfied by a generator that refuses everything.
inline constexpr int kPlantTotalPlacements = 30;

inline constexpr PlantCase kPlantCases[kPlantCaseCount] = {
    {0, 2, 101LL, 800, 41, 800, -5094661233394404331LL, 5, kPlant0},
    {0, 2, 102LL, 800, 41, 864, -3580570121466126037LL, 9, kPlant1},
    {0, 2, 103LL, 848, 41, 928, -1548374508587473873LL, 4, kPlant2},
    {0, 1, 104LL, 800, 41, 992, -2594077581101534615LL, 0, kPlant3},
    {0, 0, 105LL, 896, 41, 1056, 5899908026503481220LL, 0, kPlant4},
    {0, 3, 106LL, 800, 41, 1120, -1135304731191949262LL, 0, kPlant5},
    {1, 0, 201LL, 992, 41, 1184, -8681873901543308110LL, 4, kPlant6},
    {1, 0, 202LL, 896, 41, 1248, 5940821609515515169LL, 3, kPlant7},
    {1, 0, 203LL, 800, 41, 1312, -6671016538268501383LL, 5, kPlant8},
    {1, 3, 204LL, 800, 41, 1376, 5126586713211091158LL, 0, kPlant9},
    {1, 1, 205LL, 800, 41, 1440, -6032075021306227183LL, 0, kPlant10},
    {1, 2, 206LL, 1040, 41, 1504, -1658769246184286666LL, 0, kPlant11},
};

}  // namespace mc::test
