// Generated by tools/genref.java --sintable. Do not edit by hand.
//
// MathHelper's 65,536-entry sine table, as a hash over every bit plus a
// scattering of individual entries for diagnosis. See tools/genref.java.
//
// Regenerate with:  java tools/genref.java --sintable > tests/sin_table_vectors.hpp

#pragma once

#include "core/util/types.hpp"

namespace mc::test {

inline constexpr u64 kSinTableHash = 0x115B15B6AD9D2006ULL;

struct SinSample {
    int index;
    u32 bits;
};

inline constexpr int kSinSampleCount = 64;

inline constexpr SinSample kSinSamples[kSinSampleCount] = {
    {0, 0x00000000U},
    {1, 0x38C90FDBU},
    {16383, 0x3F800000U},
    {16384, 0x3F800000U},
    {16385, 0x3F800000U},
    {32767, 0x38C90FDBU},
    {32768, 0x250D3132U},
    {32769, 0xB8C90FDBU},
    {49151, 0xBF800000U},
    {49152, 0xBF800000U},
    {49153, 0xBF800000U},
    {65534, 0xB9490FDBU},
    {65535, 0xB8C90FDBU},
    {613, 0x3D709603U},
    {1892, 0x3E38BACFU},
    {3171, 0x3E9944F7U},
    {4450, 0x3ED3DF48U},
    {5729, 0x3F05A588U},
    {7008, 0x3F1F599FU},
    {8287, 0x3F36A919U},
    {9566, 0x3F4B3A56U},
    {10845, 0x3F5CBE46U},
    {12124, 0x3F6AF191U},
    {13403, 0x3F759DA1U},
    {14682, 0x3F7C996DU},
    {15961, 0x3F7FCA1DU},
    {17240, 0x3F7F236DU},
    {18519, 0x3F7AA7DEU},
    {19798, 0x3F7268ABU},
    {21077, 0x3F668588U},
    {22356, 0x3F572C2AU},
    {23635, 0x3F449793U},
    {24914, 0x3F2F0F30U},
    {26193, 0x3F16E5CBU},
    {27472, 0x3EF8F08EU},
    {28751, 0x3EC0587AU},
    {30030, 0x3E84DCEFU},
    {31309, 0x3E0EC535U},
    {32588, 0x3C8D5D5AU},
    {33867, 0xBDD7639CU},
    {35146, 0xBE67713FU},
    {36425, 0xBEAFDB76U},
    {37704, 0xBEE95A37U},
    {38983, 0xBF0FABEEU},
    {40262, 0xBF288268U},
    {41541, 0xBF3ED10EU},
    {42820, 0xBF52421EU},
    {44099, 0xBF628AD8U},
    {45378, 0xBF6F6CA3U},
    {46657, 0xBF78B5F8U},
    {47936, 0xBF7E4323U},
    {49215, 0xBF7FFECEU},
    {50494, 0xBF7DE24EU},
    {51773, 0xBF77F5C1U},
    {53052, 0xBF6E4FEEU},
    {54331, 0xBF6115EBU},
    {55610, 0xBF507A92U},
    {56889, 0xBF3CBDBCU},
    {58168, 0xBF262B4AU},
    {59447, 0xBF0D1A03U},
    {60726, 0xBEE3D48BU},
    {62005, 0xBEAA092DU},
    {63284, 0xBE5B6038U},
    {64563, 0xBDBEC569U},
};

}  // namespace mc::test
