#pragma once

// The host's half of a playable session: the world it has open, described to
// the other consoles in protocol-2 packets.
//
// **Why protocol 2 and not something of our own.** This console already has a
// complete protocol-2 *client* -- core/net/packets.hpp encodes and parses the
// table, core/net/chunk_payload.hpp makes and reads Map Chunks,
// `WorldStreamer::openRemote` runs a world nobody generates, and
// platform/ctr/net_play.hpp joins the two. All of that was written to talk to
// server 0.2.1 over TCP and none of it cares what carried the bytes. So a host
// that speaks the same packets gets the entire guest side for nothing, and the
// one thing that had to be built is this: the half that decides *what to say*.
//
// **The link is a byte stream, so this is a byte stream.** A protocol-2 packet
// has no length prefix -- the parser finds the next one by knowing the shape of
// this one -- so the packets are written end to end into a per-player buffer
// and the caller cuts that into link messages. core/net/link.hpp delivers them
// reliably and in order, which is the same promise TCP makes and the only one
// the parser needs.
//
// **What the host can serve is what the host has loaded -- and it loads for
// everybody.** The grid is a square around the host's own camera (see
// core/render/world_streamer.hpp: it wraps modulo its own width, so it has
// exactly one centre), so for a long time a column outside it could not be
// sent and a guest who walked past the edge of the host's render distance
// simply stopped receiving ground.
//
// `viewCentres` is the end of that. It says where every guest is; the streamer
// takes the list as **served areas** and holds their ground outside the grid,
// read from the same cache, generated by the same generator, ticked through the
// same `TickWorld` and saved by the same autosave -- everything a resident
// column gets except a mesh, which is the one thing nobody on this console is
// looking at. `Player::starved` still exists and still means "there is no
// column under them *right now*", but it is a wait while their ground is read
// or made rather than a wall they have walked into.
//
// **One thread, for the deflate.** A column is 82 KB of planes and
// `zip::compress` over it is several frames' work on an ARM11, which
// CONTRIBUTING has ruled off core 0 since long before there was a session.
// Serialising happens on the main thread, where the grid is settled and a
// borrowed column pointer is safe; only the deflate crosses. See `ColumnOven`.

#include "core/entity/arrow.hpp"
#include "core/entity/item_entity.hpp"
#include "core/entity/mob.hpp"
#include "core/net/packet_channel.hpp"
#include "core/net/packets.hpp"
#include "core/util/types.hpp"
#include "core/world/chunk.hpp"

#include <atomic>
#include <condition_variable>
#include <mutex>
#include <string>
#include <thread>
#include <vector>

namespace mc::net {

// The host's world, as the serving half needs it. Implemented by the platform:
// reading a column needs the grid and writing a block needs a renderer, and
// neither of those belongs in core/net.
class ServerWorld {
public:
    virtual ~ServerWorld() = default;

    // A column that is resident right now, or null. Good only for the length
    // of the call -- the grid drops columns in `update()`.
    virtual const world::ChunkColumn* column(i32 chunkX, i32 chunkZ) const = 0;

    // level.dat's running tick count, and the spawn point.
    virtual i64 timeTicks() const = 0;
    virtual void spawnPoint(i32* x, i32* y, i32* z) const = 0;

    // **`kh.q()` -- preparePlayerToSpawn -- for somebody else.** The spawn
    // point in level.dat is a block coordinate with no promise that anything
    // above it is air: a1.1.2 stands a fresh player at `spawnY + 1` and then
    // walks them up until nothing collides, and a server does the same for
    // every login. Without it a guest arrives inside the hillside that has
    // grown over the spawn point since the world was made, which in Survival
    // is a suffocation with no visible cause.
    //
    // Called with the column under the feet already resident, because the
    // placement is only sent once it has been -- see `streamColumns`. The
    // default does nothing, which is what a test with no blocks wants.
    virtual double settleFeet(double x, double feetY, double z) const
    {
        (void)x;
        (void)z;
        return feetY;
    }

    // **A guest's left click that finished a block.** The host runs it through
    // the same break the player's own click does, so the drop, the particles,
    // the neighbour updates and the lighting all happen once, here.
    //
    // **`heldItem` is what decides whether anything drops**, and leaving it out
    // is what made a guest's mining drop nothing at all. `in.c(III)Z` in the
    // 0.2.1 server ends `if (removed && player.canHarvestBlock(block))
    // block.harvestBlock(...)`, so the drop is the digger's tool's, not the
    // host's -- stone under a bare hand leaves nothing and under a pickaxe
    // leaves cobblestone, decided here because the guest's world has no item
    // entities of its own. It is `player.heldItem`, which the guest keeps
    // current with a Holding Change ahead of every dig and every place.
    virtual void breakBlock(i32 x, int y, i32 z, int heldItem) = 0;

    // **A guest's right click on a face**, with everything `item::rightClick`
    // needs that only the guest knows: what they are standing in, so a block
    // cannot be placed inside them, and which way they face, so a stair or a
    // chest lands the right way round.
    struct PlaceRequest {
        i32 x = 0;
        int y = 0;
        i32 z = 0;
        int face = 0;
        int item = 0;
        double playerX = 0.0;
        double playerFeetY = 0.0;
        double playerZ = 0.0;
        float yawDegrees = 0.0f;
    };
    virtual void placeBlock(const PlaceRequest& request) = 0;

    // **A guest's left click on something alive.** See `packet::UseEntity` for
    // why this exists at all at protocol 2. `item` is what they are holding,
    // which is the whole of how hard the hit lands, and the position is theirs,
    // because a struck animal is knocked away from whoever hit it.
    struct AttackRequest {
        i32 entityId = 0;
        int item = 0;
        double playerX = 0.0;
        double playerZ = 0.0;
    };
    virtual void attackEntity(const AttackRequest& request) { (void)request; }

    // **A guest's left click on the host's own player.** The one entity in the
    // session this server does not own: the host's health is the host's, the
    // way every player's is at protocol 2, so this hands the blow to whoever
    // is holding their vitals instead of resolving it here. `entityId` is the
    // host's and is not worth passing; what matters is who swung and with
    // what. See `net::IncomingHit`.
    virtual void attackHost(const AttackRequest& request) { (void)request; }

    // A line a guest typed, already prefixed with who said it, for the host's
    // own chat log.
    virtual void showChat(const std::string& line) = 0;

    // **What is lying on the ground.** The host's own pool -- an item dropped
    // by a guest is an ordinary item in this world, and one dropped here is an
    // ordinary item in theirs. Null for a world with no pool, which is what
    // the tests that do not care about items pass.
    virtual entity::ItemEntitySystem* items() { return nullptr; }

    // **What is alive.** The host runs every animal and monster -- their AI,
    // their physics and their despawn -- and the guests are told where they
    // are, exactly as a client is told by a server. Null for a world with no
    // pool.
    virtual entity::MobSystem* mobs() { return nullptr; }

    // **What is in flight or stuck in the ground**, the host's own pool. An
    // arrow a guest fires is fired here, on their behalf, and the guests are
    // told where every arrow is -- see `WorldServer::syncArrows`. Null for a
    // world with no pool.
    virtual entity::ArrowSystem* arrows() { return nullptr; }

    // **A guest's right click in the air** -- `makeUseItem`. Only the bow
    // means anything at protocol 2's end of the game: the host fires the
    // arrow from the guest's eye along their look, as theirs. The ammunition
    // is the guest's and was spent on their own console before they asked.
    struct UseRequest {
        int item = 0;
        i32 shooterEntityId = 0;
        double eyeX = 0.0, eyeY = 0.0, eyeZ = 0.0;
        float yawDegrees = 0.0f;
        float pitchDegrees = 0.0f;
    };
    virtual void useItem(const UseRequest& request) { (void)request; }

    // A guest threw something. `mx/my/mz` are blocks per tick.
    virtual void spawnItem(double x, double y, double z, item::ItemId id, int count,
                           double mx, double my, double mz)
    {
        (void)x; (void)y; (void)z; (void)id; (void)count; (void)mx; (void)my; (void)mz;
    }
};

// ---------------------------------------------------------------------------

// The deflate thread. One column in, one 0x33's worth of encoded bytes out.
//
// Two slots deep rather than one, so the main thread can hand over the next
// column in the same frame it takes the last one back and the thread is never
// idle waiting for a frame to come round.
class ColumnOven {
public:
    static constexpr int kDepth = 2;

    ColumnOven() = default;
    ~ColumnOven();

    ColumnOven(const ColumnOven&) = delete;
    ColumnOven& operator=(const ColumnOven&) = delete;

    // False when no thread could be started, in which case `offer` deflates
    // inline -- slow, but a session rather than no session.
    bool start();
    void stop();
    bool threaded() const { return running_; }

    // Hands over one column's raw planes, which are taken from `raw`. False
    // when both slots are busy, and then `raw` is untouched.
    bool offer(u8 playerId, i32 chunkX, i32 chunkZ, std::vector<u8>* raw);

    // A finished Map Chunk, encoded. False when nothing is ready.
    bool take(u8* playerId, i32* chunkX, i32* chunkZ, std::vector<u8>* encoded);

    // How many are in the oven or waiting to be taken out.
    int outstanding() const;

private:
    enum class Slot : u8 { Free, Waiting, Baking, Done };

    struct Job {
        Slot slot = Slot::Free;
        u8 playerId = 0;
        i32 chunkX = 0;
        i32 chunkZ = 0;
        std::vector<u8> raw;
        std::vector<u8> encoded;
    };

    static void threadEntry(void* self);
    void run();
    static void bake(Job& job);

    mutable std::mutex lock_;
    std::condition_variable wake_;
    Job jobs_[kDepth];
    bool stopRequested_ = false;
    bool running_ = false;

    std::thread thread_;
    void* platformThread_ = nullptr;
};

// ---------------------------------------------------------------------------

class WorldServer {
public:
    // The host and three guests -- core/net/session.hpp's cap, restated here
    // because this side has to size an array with it and core/net/link.hpp is
    // the wrong dependency for a world.
    static constexpr int kMaxPlayers = 4;

    // Chunks each way. Smaller than the console's own render distance on
    // purpose: every column in it is a deflate and 1,400-byte datagrams on a
    // shared radio, and a guest that can see eight chunks in every direction
    // has spent a minute of the link getting there.
    static constexpr int kViewDistance = 6;

    // Where a player's bytes go. False when the link could not take them now,
    // which is ordinary back-pressure: what was refused is kept and offered
    // again next frame. `playerId` is always one player -- broadcasting is
    // this class's job, because only it knows what each guest already has.
    using SendFn = bool (*)(void* ctx, u8 playerId, const u8* data, usize size);

    WorldServer();
    ~WorldServer();

    WorldServer(const WorldServer&) = delete;
    WorldServer& operator=(const WorldServer&) = delete;

    void open(ServerWorld* world, SendFn send, void* ctx, const std::string& hostName);
    void close();

    // **The host's own copy of what it is telling everybody else.**
    //
    // A host is `players_[0]`, and slot zero has no stream: it is the one
    // console in the session that is not a client of this server, so every
    // packet describing a guest went out over the radio and none of it came
    // back here. The result was a host who could see the world they were
    // serving and not the people in it -- no body, no name, nothing to aim at.
    //
    // So the packets that describe a *player* are handed here as well as sent.
    // They are the same packets, so the host's `RemoteEntities` interprets
    // them with the same code a guest uses, interpolation and all, rather than
    // a second path that could disagree about where somebody is standing.
    //
    // Only players: the items and the animals are this console's own pool
    // already, and echoing those would draw each of them twice.
    using LocalSink = void (*)(void* ctx, const Packet& packet);
    void setLocalSink(LocalSink sink, void* ctx)
    {
        localSink_ = sink;
        localCtx_ = ctx;
    }
    bool isOpen() const { return world_ != nullptr; }

    // A guest finished the link handshake. Nothing is sent until the first
    // `pump` after this, so joining never happens in the middle of a frame's
    // world updates.
    void addPlayer(u8 playerId, const std::string& name);
    void removePlayer(u8 playerId);
    int playerCount() const;

    // Bytes from one guest's stream, in order.
    void feed(u8 playerId, const u8* data, usize size);

    // Once a frame, after the world has been updated and before the frame is
    // drawn. Everything that crosses the link is decided here.
    void pump(i64 nowMillis);

    // Where the host's own player is. Called from the player's tick, which is
    // where a1.1.2's own client reports one.
    void setHostPose(double x, double feetY, double z, float yaw, float pitch);

    // **The host's arm swinging**, which is `la.w()`'s Arm Animation from the
    // one player with no stream of its own. Every guest draws it.
    void hostSwing();

    // **How the host's own player stands**: crouched, dead, or back. Every
    // guest is told on a change, with the packets a guest's own
    // `StanceReporter` sends about itself -- see `packet::EntityAction`.
    // Called every tick; nothing goes out unless something changed.
    void setHostStance(bool sneaking, bool alive);

    // **The host swinging at a guest.** The host has no stream of its own, so
    // a blow it lands has to be put on the wire here rather than falling out
    // of `feed`. False when `targetEntityId` is not a guest in this session.
    // See `packet::UseEntity`.
    bool hostAttack(i32 targetEntityId, int heldItem);

    // **The choke point every block change in the game goes through.** See
    // `WorldStreamer::setBlockWatcher`: one call per changed block, including
    // the hundreds a spreading fluid makes, so what happens here is a push
    // into a per-column list and nothing else.
    void blockChanged(i32 x, int y, i32 z);

    // A line the host typed, or one the game generated.
    void say(const std::string& text);

    // Whether this player is standing outside what the host has loaded, so
    // nothing more can be sent to them. For a line on the screen.
    bool starved(u8 playerId) const;

    // **The guests, as targets for the host's arrows**: where each one who is
    // in the world and alive is standing. Writes at most `max` and returns how
    // many. The host's own player is not here -- it is the local player of the
    // arrow tick already.
    int arrowTargets(entity::RemoteTarget* out, int max) const;

    // **One of the host's arrows struck a guest.** The guest is told "that
    // arrow hit you" -- a Use Entity from the arrow's id, announced first if
    // it never was -- and works out the cost on their own console, as they do
    // for a blow. See `packet::UseEntity`.
    void arrowStruck(i32 victimEntityId, entity::Arrow& arrow);

    // For the debug page.
    u32 columnsSent() const { return columnsSent_; }
    u32 itemsSpawned() const { return itemsSpawned_; }
    u32 mobsSpawned() const { return mobsSpawned_; }
    u32 columnsQueued() const;
    u32 blockPacketsSent() const { return blockPacketsSent_; }
    usize outboundBytes() const;

private:
    struct Pending {
        i32 chunkX = 0;
        i32 chunkZ = 0;
    };

    // **What the host remembers about somebody between visits**, keyed by the
    // name they joined under.
    //
    // A guest has no `level.dat` here -- their world is on the other console --
    // so this is the whole of their save, and it lives as long as the session
    // does. Leaving and rejoining puts them back where they were with what
    // they were carrying; a console the host has never seen starts at the
    // world's spawn point with an empty pack, which is what a fresh player in
    // a1.1.2 gets.
    struct SavedPlayer {
        std::string name;
        double x = 0.0, feetY = 0.0, z = 0.0;
        float yaw = 0.0f, pitch = 0.0f;
        bool placed = false;
        // a1.1.2's multiplayer inventory is the *client's*: it pushes all three
        // arrays every twentieth tick and the server adopts them (see
        // core/net/player_sync.hpp). So this is a copy of what they last said,
        // handed back at their next login.
        bool haveInventory = false;
        std::vector<WireStack> main;
        std::vector<WireStack> armour;
    };

public:
    // **Somebody was put somewhere other than where they should have been**,
    // because the host had no world loaded there. For a line on the screen;
    // see `kPlacementPatienceMs` in the implementation.
    bool displaced(u8 playerId) const;

    // **Where every guest is, in chunks**, so the world this console has open
    // can be made to include them.
    //
    // This is the other half of "what the host can serve is what the host has
    // loaded", up at the top of this file: the host's grid is centred on the
    // host's camera and cannot be centred on anybody else, so a guest who
    // walks out of it used to be a player standing at the edge of nothing.
    // `WorldStreamer::setServedAreas` takes this list and holds their ground
    // outside the grid -- read, generated, ticked and saved like any other,
    // just never meshed. Writes at most `max` entries and returns how many.
    //
    // A guest whose Position & Look has not been echoed yet has no view and is
    // left out: there is nowhere to load around until they say where they are.
    struct ViewCentre {
        i32 chunkX = 0;
        i32 chunkZ = 0;
    };
    int viewCentres(ViewCentre* out, int max) const;

    // The radius those centres want, which is what `ae` sends plus the ring of
    // slack `rebuildView` keeps -- a column the tracker still holds must still
    // be answerable, or the guest loses ground it is standing on.
    static constexpr int kServedRadius = kViewDistance + 1;

private:

    struct Player {
        bool used = false;
        u8 id = 0;
        i32 entityId = 0;
        std::string name;

        // The wire's own idea of where they are: feet, and the eye above it.
        double x = 0.0, feetY = 0.0, eyeY = 0.0, z = 0.0;
        float yaw = 0.0f, pitch = 0.0f;
        i16 heldItem = 0;

        bool loggedIn = false;
        // The Position & Look has gone out. Until the guest echoes it back
        // a1.1.2's server ignores every move, and so does this.
        bool placed = false;
        // When they logged in, so a placement that is waiting on ground the
        // host has not got can give up rather than wait forever. See
        // `kPlacementPatienceMs`.
        i64 loggedInMs = 0;
        // They were put somewhere other than where they asked to be, because
        // the ground there never arrived.
        bool displaced = false;
        bool spawned = false;  // the others have been told about this one

        // How they stand, as they last said: crouched, and dead until a
        // Respawn. Kept so a console that joins later is told too.
        bool sneaking = false;
        bool dead = false;

        // Positions were withheld while this guest's outbox was backed up, and
        // the current ones are owed. See `broadcastMove`.
        bool movesOwed = false;

        // The centre the sent set was built around.
        i32 viewX = 0, viewZ = 0;
        bool viewSet = false;

        // Columns this guest holds, and the ones still owed. Both are small:
        // (2 * kViewDistance + 1)^2 is 169 at six.
        std::vector<i64> holds;
        std::vector<Pending> owed;

        // **Columns serialised for this guest and not yet handed back by the
        // oven**, and the ones among them that the world has changed since.
        //
        // This pair closes the one window in which a guest could end up
        // holding a column that is quietly wrong forever. The bytes in the
        // oven are a photograph taken when the column was offered; a block
        // written while it is in there is in neither the photograph (too late)
        // nor a Block Change (the guest does not hold the column yet, so
        // nobody sends it one). So such a column is marked and thrown away
        // when it comes out, and the coordinate goes back on `owed` to be
        // photographed again. It costs one extra deflate for an edit that
        // lands inside a two-frame window.
        std::vector<i64> inOven;
        std::vector<i64> stale;

        bool starved = false;

        // Bytes on their way out, and the guest's own stream coming in.
        std::vector<u8> outbox;
        std::vector<u8> in;
        usize inStart = 0;
        Packet parsed;

        // What was sent last, so a move that changed nothing is not sent.
        i32 lastSentX = 0, lastSentY = 0, lastSentZ = 0;
        i8 lastSentYaw = 0, lastSentPitch = 0;
        bool everSent = false;
    };

    // One column's worth of changed blocks, waiting to be sent.
    struct DirtyColumn {
        i32 chunkX = 0;
        i32 chunkZ = 0;
        // Packed the way 0x34 packs them: x << 12 | z << 8 | y, chunk-local.
        std::vector<u16> blocks;
        bool overflowed = false;
    };

    Player* find(u8 playerId);

    // By the id everything on the wire names them with, host included.
    Player* playerByEntity(i32 entityId);

    // `packet_` as the Named Entity Spawn that puts `player` on somebody's
    // screen, where they are now.
    void fillNamedSpawn(const Player& player);
    const Player* find(u8 playerId) const;

    void write(Player& player, const Packet& packet);
    void broadcast(const Packet& packet, u8 exceptPlayerId);

    // **A position, which is state and not an event.** `broadcast`, except that
    // a guest whose outbox is already backed up is not given it: a newer one
    // will exist before it could be delivered, and queueing it would put every
    // block change behind a wall of places things used to be. Such a guest is
    // marked owed and sent every current position once it has caught up; see
    // `resendPositions`. `announceMove` tells the host too, as `announce` does.
    void broadcastMove(const Packet& packet, u8 exceptPlayerId);
    void announceMove(const Packet& packet, u8 exceptPlayerId);
    void resendPositions(Player& player);

    // `broadcast`, and the host is told too. For the packets that describe a
    // player -- see `setLocalSink`.
    void announce(const Packet& packet, u8 exceptPlayerId);
    void flush(Player& player);

    void login(Player& player);
    void rebuildView(Player& player);
    void streamColumns();
    void takeOven();
    void sendBlockChanges();
    void sendEntities(i64 nowMillis);

    // **The items on the ground, as the guests see them.** New ones are given
    // an id and announced, ones that have gone are destroyed, ones that moved
    // are placed again, and a guest standing on one picks it up -- because on
    // this side of the link the host is the only one allowed to decide that.
    void syncItems(i64 nowMillis);
    void syncMobs(i64 nowMillis);
    void collectFor(Player& player, entity::ItemEntitySystem& items);

    // **The arrows, as the guests see them.** Not in a1.1.2 at all -- see
    // `packet::kObjectArrow` -- and otherwise `syncItems` again: an id and a
    // Vehicle Spawn for a new one, a teleport each tick for one that moved, a
    // Destroy for one that went, and a guest walking over their own stuck
    // arrow takes it back.
    void syncArrows(i64 nowMillis);
    void collectArrowsFor(Player& player, entity::ArrowSystem& arrows);
    // Tells every guest about `arrow` now, if they have not been told; gives it
    // an id first when it has none.
    void announceArrow(entity::Arrow& arrow);

    // A guest still waiting for ground that is never coming. See
    // `kPlacementPatienceMs`.
    void placeStragglers();

    // What the host remembers about a name, and the two halves of keeping it.
    SavedPlayer* savedFor(const std::string& name);
    void remember(const Player& player);
    void onPacket(Player& player, const Packet& packet);

    // The host's own player, as an entity the guests are told about.
    Player& host() { return players_[0]; }

    ServerWorld* world_ = nullptr;
    SendFn send_ = nullptr;
    void* ctx_ = nullptr;

    LocalSink localSink_ = nullptr;
    void* localCtx_ = nullptr;

    Player players_[kMaxPlayers];
    ColumnOven oven_;

    std::vector<DirtyColumn> dirty_;
    std::vector<u8> scratch_;   // serializeRegion's output, reused
    Packet packet_;             // the packet being built, reused

    // One item the guests have been told about, and where they were last told
    // it was. Small: the pool starts at 64 and a1.1.2 never has many more.
    struct KnownItem {
        i32 entityId = 0;
        i32 x = 0, y = 0, z = 0;
        bool seen = false;
    };
    std::vector<KnownItem> knownItems_;

    // The same bookkeeping for what is alive. Separate from the items because
    // a spawn is a different packet and because the two pools are.
    struct KnownMob {
        i32 entityId = 0;
        i32 x = 0, y = 0, z = 0;
        i8 yaw = 0, pitch = 0;
        bool seen = false;
        // What the guests have been told about its hits and its death. See
        // `packet::EntityStatus`.
        u8 hurtSerial = 0;
        bool deathSent = false;
    };
    std::vector<KnownMob> knownMobs_;

    // And for the arrows, which also carry a heading worth sending.
    struct KnownArrow {
        i32 entityId = 0;
        i32 x = 0, y = 0, z = 0;
        i8 yaw = 0, pitch = 0;
        bool seen = false;
    };
    std::vector<KnownArrow> knownArrows_;

    std::vector<SavedPlayer> saved_;

    i64 nowMs_ = 0;
    i64 lastTimeMs_ = 0;
    i64 lastEntityMs_ = 0;
    i64 lastItemMs_ = 0;
    i64 lastMobMs_ = 0;
    i64 lastArrowMs_ = 0;
    // Whether the host's own player has reported a position yet, which decides
    // where a joiner lands. See `addPlayer`.
    bool hostPosed_ = false;
    i32 nextEntityId_ = 1;

    u32 columnsSent_ = 0;
    u32 blockPacketsSent_ = 0;
    u32 itemsSpawned_ = 0;
    u32 mobsSpawned_ = 0;
    u32 arrowsSpawned_ = 0;
};

}  // namespace mc::net
