#pragma once

// **Crafting** -- CraftingManager (`dw`), the shaped recipe (`bv`), the two
// crafting containers (`n` the player's 2 x 2, `et` the workbench's 3 x 3) and
// the result slot (`an`).
//
// The recipes are the jar's own list, in its own order, generated by
// `tools/genref.java --recipes` into data/<version>/recipes.json. What is
// transcribed here is the matching, which is code:
//
//   * **Every recipe is shaped** in a1.1.2. `dw.a([I)Lev;` walks the list and
//     returns the first whose `bv.a([I)Z` accepts the grid.
//   * A recipe is tried at **every offset** its width and height allow inside
//     the 3 x 3, and at each offset **mirrored first, then straight**. Every
//     cell of the 3 x 3 must agree -- a blank outside the recipe must be blank --
//     so a stick in the corner of a pickaxe grid is not a pickaxe.
//   * **The 2 x 2 grid is matched as a 3 x 3** with its four cells in the top
//     left and the rest blank, which is why a torch can be made in the
//     inventory and a pickaxe cannot.
//   * The result is `new ItemStack(id, count)`, damage zero.
//   * **Taking the result spends one of every occupied cell** -- `an.a()`, which
//     calls `decrStackSize(i, 1)` on each -- and every change to the grid
//     recomputes the result, which is `gu` telling its container.

#include "core/item/item_stack.hpp"
#include "core/util/types.hpp"

namespace mc::item {

inline constexpr int kCraftingCells = 9;

struct CraftingGrid {
    // 2 for the player's own, 3 for the workbench. Cells are `x + y * width`.
    int width = 3;
    ItemStack cells[kCraftingCells];
    ItemStack result;

    int size() const { return width * width; }
};

// `dw.a([I)Lev;` -- the result for nine item ids (-1 for a blank) laid out
// `x + y * 3`, or an empty stack when nothing matches.
ItemStack matchRecipe(const i16 ids[kCraftingCells]);

// `et.a(Lgh;)V` / `n.a(Lgh;)V` -- recompute the result from the cells.
void refreshResult(CraftingGrid& grid);

// `an.a()V` -- one off every occupied cell, then the result again.
void consumeIngredients(CraftingGrid& grid);

}  // namespace mc::item
