#!/usr/bin/env python3
"""Turn a version manifest into generated build inputs.

    tools/configure.py <version-id> <output-dir>

Reads versions/<id>.json and writes, into <output-dir>:

    version_config.hpp   constants + feature flags as constexpr
    version_slots.hpp    includes for the selected slot implementations
    version.cmake        source dirs and packaging metadata for CMake
    <id>.rsf             makerom config with packaging fields substituted

Nothing here is parsed at runtime -- see docs/build-versions.md.
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Every slot a version must fill. Adding one here makes it required everywhere,
# which is deliberate: a version that silently lacks a subsystem is a bug.
SLOTS = ("storage", "strings", "items", "worldgen", "containers", "entitydata")

BANNER = "// GENERATED by tools/configure.py from versions/{id}.json -- do not edit.\n"


def camel(name: str) -> str:
    """snake_case or camelCase -> PascalCase, preserving existing inner capitals."""
    return "".join(p[:1].upper() + p[1:] for p in name.replace("-", "_").split("_"))


def c_bool(value: bool) -> str:
    return "true" if value else "false"


def load_manifest(version_id: str) -> dict:
    path = REPO / "versions" / f"{version_id}.json"
    if not path.is_file():
        available = sorted(p.stem for p in (REPO / "versions").glob("*.json"))
        sys.exit(f"configure: no manifest {path}\n  available: {', '.join(available) or '(none)'}")

    manifest = json.loads(path.read_text())

    missing = [s for s in SLOTS if s not in manifest.get("slots", {})]
    if missing:
        sys.exit(f"configure: {path.name} does not fill slot(s): {', '.join(missing)}")

    return manifest


def write_version_config(out: Path, m: dict) -> None:
    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        "\nnamespace mcver {\n",
        f'\ninline constexpr char kId[]       = "{m["id"]}";\n',
        f'inline constexpr char kDisplay[]  = "{m["display"]}";\n',
        f'inline constexpr char kAppTitle[] = "{m["appTitle"]}";\n',
        "\n",
    ]

    for key, value in m["constants"].items():
        lines.append(f"inline constexpr int k{camel(key)} = {value};\n")

    lines.append("\n")
    for key, value in m["features"].items():
        name = key if key.startswith("has") else f"has{camel(key)}"
        lines.append(f"inline constexpr bool k{camel(name)} = {c_bool(value)};\n")

    lines.append("\n// Slot bindings arrive via version_slots.hpp.\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "version_config.hpp").write_text("".join(lines))


def write_version_slots(out: Path, m: dict) -> list:
    """Include each selected slot's binding header. Report the ones not built yet."""
    lines = [BANNER.format(id=m["id"]), "#pragma once\n", '\n#include "version_config.hpp"\n\n']
    unfilled = []

    for slot in SLOTS:
        impl = m["slots"][slot]
        header = REPO / "src" / "impl" / slot / impl / "slot.hpp"
        if header.is_file():
            lines.append(f'#include "impl/{slot}/{impl}/slot.hpp"\n')
        else:
            unfilled.append(f"{slot}={impl}")
            lines.append(f"// TODO({slot}): {impl} has no slot.hpp yet\n")

    (out / "version_slots.hpp").write_text("".join(lines))
    return unfilled


def write_cmake(out: Path, m: dict) -> None:
    slot_dirs = [f"src/impl/{slot}/{m['slots'][slot]}" for slot in SLOTS]
    pkg = m["packaging"]

    lines = [
        BANNER.format(id=m["id"]).replace("//", "#"),
        f'set(MCVER_ID "{m["id"]}")\n',
        f'set(MCVER_DISPLAY "{m["display"]}")\n',
        f'set(MCVER_APP_TITLE "{m["appTitle"]}")\n',
        f'set(MCVER_APP_DESCRIPTION "{m["appDescription"]}")\n',
        f'set(MCVER_UNIQUE_ID "{pkg["uniqueId"]}")\n',
        f'set(MCVER_PRODUCT_CODE "{pkg["productCode"]}")\n',
        f'set(MCVER_ICON_BADGE "{pkg["iconBadge"]}")\n',
        f'set(MCVER_DATA_DIR "{m["data"]}")\n',
        "set(MCVER_SLOT_DIRS\n",
    ]
    lines += [f'\t"{d}"\n' for d in slot_dirs]
    lines.append(")\n")

    (out / "version.cmake").write_text("".join(lines))


def pascal(name: str) -> str:
    """snake_case -> PascalCase, for generated enumerator names."""
    return "".join(part.capitalize() for part in name.split("_"))


def write_blocks(out: Path, m: dict) -> bool:
    """Turn data/<version>/blocks.json into a constexpr table.

    The table is indexed directly by block id, so a lookup is a bounds check
    and a load -- no map and nothing to build at startup. Ids the version does
    not define are filled with a visible unknown block rather than left as a
    hole, because a world can legally contain one.
    """
    source = REPO / m["data"] / "blocks.json"
    if not source.is_file():
        (out / "blocks.hpp").write_text(
            BANNER.format(id=m["id"]) + "#pragma once\n"
            "// No blocks.json for this version yet.\n")
        return False

    doc = json.loads(source.read_text())
    blocks = {entry["id"]: entry for entry in doc["blocks"]}

    # Pre-Anvil ids are one byte on disk and on the wire. The table covers the
    # whole range so that any id a file can hold is in bounds.
    table_size = 256
    over = sorted(i for i in blocks if i >= table_size)
    if over:
        sys.exit(f"configure: block ids {over} do not fit a {table_size}-entry table")

    def faces(entry) -> str:
        """The six per-face atlas tiles. A block with one texture everywhere
        carries no `faces` in the JSON, because 46 of the 70 would otherwise be
        six copies of one number; it is expanded here so the mesher can index
        without a branch.

        Alpha's BlockDoor answers with a *negative* tile index to mean "mirror
        this face horizontally", which the table cannot carry. Doors do not
        render as cubes, so the magnitude is stored and the sign dropped -- but
        only for a block the mesher will not draw. A mirrored face on a cube
        would be silently wrong, so it stops the build instead.
        """
        tiles = entry.get("faces") or [entry.get("texture", 0)] * 6
        mirrored = [t for t in tiles if t < 0]
        if mirrored and entry["render"] == "cube":
            sys.exit(f"configure: block {entry['id']} ({entry['name']}) renders "
                     f"as a cube but wants a mirrored face texture {mirrored}; "
                     "the vertex format has no flip bit")
        return "{" + ", ".join(str(abs(t)) for t in tiles) + "}"

    # Materials are the jar's own grouping, and blocks.json carries the
    # obfuscated field name for each. The runtime asks three things of it --
    # are these two blocks the same material, is this one solid, and is it ice
    # -- so the names become a dense index here. Sorted, so the numbering is
    # stable across runs rather than depending on dict order.
    material_names = sorted({e["material"] for e in blocks.values()
                             if e.get("material") is not None})
    material_index = {name: i + 1 for i, name in enumerate(material_names)}

    # Ice is the one material the engine has to recognise by name rather than
    # by comparing two blocks: a fluid draws no face against it, and that rule
    # is a bare singleton identity check in the jar with no property behind it.
    # Ice's material is a plain `new Material()` exactly like stone's, so there
    # is nothing in the table to derive it from -- it has to be named.
    #
    # 0 when the version has no block called "ice", and 0 is a material no
    # constructed block ever takes, so the check simply never fires.
    ice = next((e for e in blocks.values() if e["name"] == "ice"), None)
    ice_material = material_index.get(ice["material"], 0) if ice else 0

    def definition(entry) -> str:
        if entry is None:
            return ('{"unknown", 0.0f, 0.0f, 0, {0, 0, 0, 0, 0, 0}, '
                    "RenderType::Cube, 0, 0, 255, true, true, true, false, true, false}")
        # repr keeps the decimal point: "100f" is not a float literal, "100.0f"
        # is, and %g drops the point for integral values.
        hardness = repr(float(entry["hardness"]))
        resistance = repr(float(entry["resistance"]))
        return (
            f'{{"{entry["name"]}", {hardness}f, {resistance}f, '
            f'{entry.get("texture", 0)}, {faces(entry)}, '
            f'RenderType::{pascal(entry["render"])}, '
            f'{material_index.get(entry.get("material"), 0)}, '
            f'{entry["light"]}, {entry["opacity"]}, '
            f'{c_bool(entry["opaque"])}, {c_bool(entry["fullCube"])}, '
            f'{c_bool(entry.get("opaqueCube", entry["opaque"]))}, '
            f'{c_bool(entry.get("translucent", False))}, '
            f'{c_bool(entry.get("solid", False))}, true}}'
        )

    # Air's material is the jar's too -- every block that uses it is the same
    # "nothing here" -- but id 0 is never constructed, so it takes index 0,
    # which no real material has.
    air = {"id": 0, "name": "air", "hardness": 0.0, "resistance": 0.0,
           "texture": 0, "render": "none", "light": 0, "opacity": 0,
           "opaque": False, "fullCube": False, "opaqueCube": False, "solid": False}

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/block/block_def.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::block::BlockDef;\n",
        "using mc::block::RenderType;\n",
        "\n// Named ids, so no literal block number appears anywhere else.\n",
        "enum class Block : mc::block::BlockId {\n",
        "    Air = 0,\n",
    ]
    for bid in sorted(blocks):
        lines.append(f"    {pascal(blocks[bid]['name'])} = {bid},\n")
    lines.append("};\n")

    lines.append(f"\ninline constexpr int kBlockTableSize = {table_size};\n")
    lines.append(f"inline constexpr int kBlockCount = {len(blocks) + 1};\n")
    lines.append("\n// The material a fluid refuses to draw a face against, "
                 "besides its own.\n// 0 means this version has none.\n")
    lines.append(f"inline constexpr mc::u8 kIceMaterial = {ice_material};\n")
    lines.append("\ninline constexpr BlockDef kUnknownBlock =\n    "
                 + definition(None) + ";\n")
    lines.append("\ninline constexpr BlockDef kBlocks[kBlockTableSize] = {\n")
    for bid in range(table_size):
        entry = air if bid == 0 else blocks.get(bid)
        label = entry["name"] if entry else "unknown"
        lines.append(f"    /* {bid:3} {label:<22} */ {definition(entry)},\n")
    lines.append("};\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "blocks.hpp").write_text("".join(lines))
    return True


def write_rsf(out: Path, m: dict) -> None:
    template = REPO / "packaging" / "3dalpha.rsf.in"
    if not template.is_file():
        return
    pkg = m["packaging"]
    text = (
        template.read_text()
        .replace("@APP_TITLE@", m["appTitle"])
        .replace("@PRODUCT_CODE@", pkg["productCode"])
        .replace("@UNIQUE_ID@", pkg["uniqueId"])
    )
    (out / f"{m['id']}.rsf").write_text(text)


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)

    version_id, out_dir = sys.argv[1], Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    m = load_manifest(version_id)
    write_version_config(out_dir, m)
    unfilled = write_version_slots(out_dir, m)
    write_cmake(out_dir, m)
    write_rsf(out_dir, m)
    has_blocks = write_blocks(out_dir, m)

    print(f"configure: {m['display']} (protocol {m['constants']['protocol']}) -> {out_dir}")
    if not has_blocks:
        print(f"configure: no {m['data']}/blocks.json yet")
    if unfilled:
        print(f"configure: slots not implemented yet: {', '.join(unfilled)}")


if __name__ == "__main__":
    main()
