#!/usr/bin/env python3
"""Turn a version manifest into generated build inputs.

    tools/configure.py <version-id> <output-dir>

Reads versions/<id>.json and writes, into <output-dir>:

    version_config.hpp   constants + feature flags as constexpr
    version_slots.hpp    includes for the selected slot implementations
    version.cmake        source dirs and packaging metadata for CMake
    <id>.rsf             makerom config with packaging fields substituted

Nothing here is parsed at runtime -- see docs/build-versions.md.
"""

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

# Every slot a version must fill. Adding one here makes it required everywhere,
# which is deliberate: a version that silently lacks a subsystem is a bug.
SLOTS = ("storage", "strings", "items", "worldgen", "containers", "entitydata")

BANNER = "// GENERATED by tools/configure.py from versions/{id}.json -- do not edit.\n"


def camel(name: str) -> str:
    """snake_case or camelCase -> PascalCase, preserving existing inner capitals."""
    return "".join(p[:1].upper() + p[1:] for p in name.replace("-", "_").split("_"))


def c_bool(value: bool) -> str:
    return "true" if value else "false"


def load_manifest(version_id: str) -> dict:
    path = REPO / "versions" / f"{version_id}.json"
    if not path.is_file():
        available = sorted(p.stem for p in (REPO / "versions").glob("*.json"))
        sys.exit(f"configure: no manifest {path}\n  available: {', '.join(available) or '(none)'}")

    manifest = json.loads(path.read_text())

    missing = [s for s in SLOTS if s not in manifest.get("slots", {})]
    if missing:
        sys.exit(f"configure: {path.name} does not fill slot(s): {', '.join(missing)}")

    return manifest


def write_version_config(out: Path, m: dict) -> None:
    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        "\nnamespace mcver {\n",
        f'\ninline constexpr char kId[]       = "{m["id"]}";\n',
        f'inline constexpr char kDisplay[]  = "{m["display"]}";\n',
        f'inline constexpr char kAppTitle[] = "{m["appTitle"]}";\n',
        "\n",
    ]

    for key, value in m["constants"].items():
        lines.append(f"inline constexpr int k{camel(key)} = {value};\n")

    lines.append("\n")
    for key, value in m["features"].items():
        name = key if key.startswith("has") else f"has{camel(key)}"
        lines.append(f"inline constexpr bool k{camel(name)} = {c_bool(value)};\n")

    lines.append("\n// Slot bindings arrive via version_slots.hpp.\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "version_config.hpp").write_text("".join(lines))


def write_version_slots(out: Path, m: dict) -> list:
    """Include each selected slot's binding header. Report the ones not built yet."""
    lines = [BANNER.format(id=m["id"]), "#pragma once\n", '\n#include "version_config.hpp"\n\n']
    unfilled = []

    for slot in SLOTS:
        impl = m["slots"][slot]
        header = REPO / "src" / "impl" / slot / impl / "slot.hpp"
        if header.is_file():
            lines.append(f'#include "impl/{slot}/{impl}/slot.hpp"\n')
        else:
            unfilled.append(f"{slot}={impl}")
            lines.append(f"// TODO({slot}): {impl} has no slot.hpp yet\n")

    (out / "version_slots.hpp").write_text("".join(lines))
    return unfilled


def write_cmake(out: Path, m: dict) -> None:
    slot_dirs = [f"src/impl/{slot}/{m['slots'][slot]}" for slot in SLOTS]
    pkg = m["packaging"]

    lines = [
        BANNER.format(id=m["id"]).replace("//", "#"),
        f'set(MCVER_ID "{m["id"]}")\n',
        f'set(MCVER_DISPLAY "{m["display"]}")\n',
        f'set(MCVER_APP_TITLE "{m["appTitle"]}")\n',
        f'set(MCVER_APP_DESCRIPTION "{m["appDescription"]}")\n',
        f'set(MCVER_UNIQUE_ID "{pkg["uniqueId"]}")\n',
        f'set(MCVER_PRODUCT_CODE "{pkg["productCode"]}")\n',
        f'set(MCVER_ICON_BADGE "{pkg["iconBadge"]}")\n',
        f'set(MCVER_DATA_DIR "{m["data"]}")\n',
        "set(MCVER_SLOT_DIRS\n",
    ]
    lines += [f'\t"{d}"\n' for d in slot_dirs]
    lines.append(")\n")

    (out / "version.cmake").write_text("".join(lines))


def pascal(name: str) -> str:
    """snake_case -> PascalCase, for generated enumerator names."""
    return "".join(part.capitalize() for part in name.split("_"))


def write_blocks(out: Path, m: dict) -> bool:
    """Turn data/<version>/blocks.json into a constexpr table.

    The table is indexed directly by block id, so a lookup is a bounds check
    and a load -- no map and nothing to build at startup. Ids the version does
    not define are filled with a visible unknown block rather than left as a
    hole, because a world can legally contain one.
    """
    source = REPO / m["data"] / "blocks.json"
    if not source.is_file():
        (out / "blocks.hpp").write_text(
            BANNER.format(id=m["id"]) + "#pragma once\n"
            "// No blocks.json for this version yet.\n")
        return False

    doc = json.loads(source.read_text())
    blocks = {entry["id"]: entry for entry in doc["blocks"]}

    # **Which ids the mesher's fast path can draw**, folded here rather than
    # asked at runtime. A standard block whose render bounds fill its cell for
    # every metadata value goes down the cube stream; anything else cannot,
    # because that stream stores whole-block corners. The bounds live in
    # selection.json, which is generated separately, so this is the one column
    # of blocks.hpp that reads another data file -- and it is worth it: asking
    # the two tables separately cost 3.3 us a section on the dev host.
    #
    # A version with no selection.json yet gets `true` for every standard
    # block, which is the behaviour this project had before boxes existed.
    selection_path = REPO / m["data"] / "selection.json"
    always_unit = {}
    # **Which metadata values a ray sees when it is allowed to hit liquids**,
    # as a sixteen-bit mask -- the other column of selection.json that belongs
    # on a block rather than in a shape table. A version without the file yet
    # falls back to the `targetable` bool broadcast over every metadata, which
    # is what this project did before a bucket existed.
    liquid_mask = {}
    if selection_path.is_file():
        selection = json.loads(selection_path.read_text())
        unit_shape = selection["shapes"].index([0.0, 0.0, 0.0, 1.0, 1.0, 1.0])
        for key, row in selection["index"].items():
            always_unit[int(key)] = all(shape == unit_shape for shape in row)
        for key, mask in selection.get("targetableLiquids", {}).items():
            liquid_mask[int(key)] = mask

    def liquid_targets(entry) -> int:
        if entry is None:
            return 0
        if entry["id"] in liquid_mask:
            return liquid_mask[entry["id"]]
        return 0xFFFF if entry["targetable"] else 0

    def unit_cube(entry) -> bool:
        if entry is None or entry["render"] != "cube":
            return False
        # A furnace fills its cell, but the fast path draws `faces` and cannot
        # read metadata, so it goes round by the slower one that can.
        if "metadataFaces" in entry:
            return False
        # And a chest fills its cell, but the fast path cannot read a
        # *neighbour* either -- which is the whole of what its front and its
        # double-chest halves are. Same detour, same reason.
        if entry.get("worldTexture", "none") != "none":
            return False
        return always_unit.get(entry["id"], True)

    # Pre-Anvil ids are one byte on disk and on the wire. The table covers the
    # whole range so that any id a file can hold is in bounds.
    table_size = 256
    over = sorted(i for i in blocks if i >= table_size)
    if over:
        sys.exit(f"configure: block ids {over} do not fit a {table_size}-entry table")

    def faces(entry) -> str:
        """The six per-face atlas tiles. A block with one texture everywhere
        carries no `faces` in the JSON, because 46 of the 70 would otherwise be
        six copies of one number; it is expanded here so the mesher can index
        without a branch.

        Alpha's BlockDoor answers with a *negative* tile index to mean "mirror
        this face horizontally", which the table cannot carry. Doors do not
        render as cubes, so the magnitude is stored and the sign dropped -- but
        only for a block the mesher will not draw. A mirrored face on a cube
        would be silently wrong, so it stops the build instead. The door's
        mirror depends on metadata anyway, so `addDoor` (core/mesh/shapes.cpp)
        re-derives it per face from `BlockDoor.getBlockTexture` and this
        no-metadata row could not have carried it.
        """
        tiles = entry.get("faces") or [entry.get("texture", 0)] * 6
        mirrored = [t for t in tiles if t < 0]
        if mirrored and entry["render"] == "cube":
            sys.exit(f"configure: block {entry['id']} ({entry['name']}) renders "
                     f"as a cube but wants a mirrored face texture {mirrored}; "
                     "the vertex format has no flip bit")
        return "{" + ", ".join(str(abs(t)) for t in tiles) + "}"

    # Materials are the jar's own grouping, and blocks.json carries the
    # obfuscated field name for each. The runtime asks three things of it --
    # are these two blocks the same material, is this one solid, and is it ice
    # -- so the names become a dense index here. Sorted, so the numbering is
    # stable across runs rather than depending on dict order.
    material_names = sorted({e["material"] for e in blocks.values()
                             if e.get("material") is not None})
    material_index = {name: i + 1 for i, name in enumerate(material_names)}

    # Ice is the one material the engine has to recognise by name rather than
    # by comparing two blocks: a fluid draws no face against it, and that rule
    # is a bare singleton identity check in the jar with no property behind it.
    # Ice's material is a plain `new Material()` exactly like stone's, so there
    # is nothing in the table to derive it from -- it has to be named.
    #
    # 0 when the version has no block called "ice", and 0 is a material no
    # constructed block ever takes, so the check simply never fires.
    ice = next((e for e in blocks.values() if e["name"] == "ice"), None)
    ice_material = material_index.get(ice["material"], 0) if ice else 0

    # **The footstep table**, nine rows shared by seventy blocks. Emitted as a
    # table plus an index rather than four columns on every row, because that
    # is the shape the jar has: `Block.stepSound` is a pointer to one of nine
    # singletons, and two blocks that share one are the *same* sound rather
    # than two rows that happen to agree.
    #
    # Index 0 is "no sound", which no real block takes -- air and any id this
    # build does not know land there, and a lookup that returns an empty name
    # is silence rather than a branch at every call site.
    step_fields = sorted({e["stepSound"] for e in blocks.values()
                          if e.get("stepSound") is not None})
    step_index = {name: i + 1 for i, name in enumerate(step_fields)}

    def definition(entry) -> str:
        if entry is None:
            # Shape::FullCube rather than None: an id this build does not
            # know is far better treated as something to stand on than as
            # something to fall through.
            return ('{"unknown", 0.0f, 0.0f, 0, {0, 0, 0, 0, 0, 0}, '
                    "RenderType::Cube, Shape::FullCube, true, 0.6f, true, "
                    "0xFFFF, 0, 0, 255, true, true, true, false, true, "
                    "TickBehaviour::None, 10, false, 0, 0, false, false, 0, "
                    "Contact::None, WorldTexture::None}")
        # repr keeps the decimal point: "100f" is not a float literal, "100.0f"
        # is, and %g drops the point for integral values.
        hardness = repr(float(entry["hardness"]))
        resistance = repr(float(entry["resistance"]))
        return (
            f'{{"{entry["name"]}", {hardness}f, {resistance}f, '
            f'{entry.get("texture", 0)}, {faces(entry)}, '
            f'RenderType::{pascal(entry["render"])}, '
            f'Shape::{pascal(entry["shape"])}, '
            f'{c_bool(unit_cube(entry))}, '
            f'{repr(float(entry["slipperiness"]))}f, '
            f'{c_bool(entry["targetable"])}, '
            f'0x{liquid_targets(entry):04X}, '
            f'{material_index.get(entry.get("material"), 0)}, '
            f'{entry["light"]}, {entry["opacity"]}, '
            f'{c_bool(entry["opaque"])}, {c_bool(entry["fullCube"])}, '
            f'{c_bool(entry.get("opaqueCube", entry["opaque"]))}, '
            f'{c_bool(entry.get("translucent", False))}, '
            f'{c_bool(entry.get("solid", False))}, '
            f'TickBehaviour::{pascal(entry.get("tick", "none"))}, '
            f'{entry.get("tickRate", 10)}, '
            f'{c_bool(entry.get("tickRandomly", False))}, '
            f'{entry.get("burnEncourage", 0)}, {entry.get("burnCatch", 0)}, '
            f'{c_bool(entry.get("canBurn", False))}, true, '
            f'{step_index.get(entry.get("stepSound"), 0)}, '
            f'Contact::{pascal(entry.get("contact", "none"))}, '
            f'WorldTexture::{pascal(entry.get("worldTexture", "none"))}}}'
        )

    # Air's material is the jar's too -- every block that uses it is the same
    # "nothing here" -- but id 0 is never constructed, so it takes index 0,
    # which no real material has.
    air = {"id": 0, "name": "air", "hardness": 0.0, "resistance": 0.0,
           "texture": 0, "render": "none", "shape": "none", "slipperiness": 0.6, "targetable": False,
           "light": 0, "opacity": 0,
           "opaque": False, "fullCube": False, "opaqueCube": False, "solid": False}

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/block/block_def.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::block::BlockDef;\n",
        "using mc::block::RenderType;\n",
        "using mc::block::Shape;\n",
        "using mc::block::TickBehaviour;\n",
        "using mc::block::Contact;\n",
        "using mc::block::WorldTexture;\n",
        "\n// Named ids, so no literal block number appears anywhere else.\n",
        "enum class Block : mc::block::BlockId {\n",
        "    Air = 0,\n",
    ]
    for bid in sorted(blocks):
        lines.append(f"    {pascal(blocks[bid]['name'])} = {bid},\n")
    lines.append("};\n")

    lines.append(f"\ninline constexpr int kBlockTableSize = {table_size};\n")
    lines.append(f"inline constexpr int kBlockCount = {len(blocks) + 1};\n")
    lines.append("\n// The material a fluid refuses to draw a face against, "
                 "besides its own.\n// 0 means this version has none.\n")
    lines.append(f"inline constexpr mc::u8 kIceMaterial = {ice_material};\n")

    # The footstep table. Index 0 is the silent row, which air and any unknown
    # id take; the rest are the jar's nine singletons in field order.
    sounds = doc.get("stepSounds", {})
    lines.append("\n// `Block.stepSound`, as a table indexed by "
                 "`BlockDef::stepSound`.\n// Row 0 is silence; no constructed "
                 "block takes it.\n")
    lines.append(f"inline constexpr int kStepSoundCount = {len(step_fields) + 1};\n")
    lines.append("inline constexpr mc::block::StepSound "
                 "kStepSounds[kStepSoundCount] = {\n")
    lines.append('    {"", "", 0.0f, 0.0f},\n')
    for name in step_fields:
        row = sounds.get(name)
        if row is None:
            sys.exit(f"configure: blocks.json has no stepSounds entry for {name!r}")
        lines.append(f'    /* {name} */ {{"{row["step"]}", "{row["break"]}", '
                     f'{repr(float(row["volume"]))}f, '
                     f'{repr(float(row["pitch"]))}f}},\n')
    lines.append("};\n")
    lines.append("\ninline constexpr BlockDef kUnknownBlock =\n    "
                 + definition(None) + ";\n")
    lines.append("\ninline constexpr BlockDef kBlocks[kBlockTableSize] = {\n")
    for bid in range(table_size):
        entry = air if bid == 0 else blocks.get(bid)
        label = entry["name"] if entry else "unknown"
        lines.append(f"    /* {bid:3} {label:<22} */ {definition(entry)},\n")
    lines.append("};\n")

    # **Faces that follow the block's own metadata**, which in a1.1.2 is the
    # furnace's mouth. Beside the table rather than in it: two blocks out of
    # 256 want sixteen rows of six, and the row the mesher's inner loop loads
    # should not grow by 192 bytes to carry them. Row 0 of the index is "none";
    # the table itself always has at least one row so it is never zero-sized.
    tabled = [bid for bid in sorted(blocks) if "metadataFaces" in blocks[bid]]
    lines.append("\n// `metadataFaces`: [row][metadata][face] -> atlas tile, for a block whose\n"
                 "// in-world faces follow its own metadata. kMetadataFaceRow[id] is the row\n"
                 "// plus one, and 0 for every block whose faces are `BlockDef::faces`.\n")
    lines.append(f"inline constexpr int kMetadataFaceTableCount = {max(len(tabled), 1)};\n")
    lines.append("inline constexpr mc::u16 "
                 "kMetadataFaces[kMetadataFaceTableCount][16][6] = {\n")
    for bid in tabled:
        rows = blocks[bid]["metadataFaces"]
        if len(rows) != 16 or any(len(row) != 6 for row in rows):
            sys.exit(f"configure: block {bid}'s metadataFaces is not 16 rows of 6")
        lines.append(f"    /* {bid} {blocks[bid]['name']} */ {{\n")
        for row in rows:
            lines.append("        {" + ", ".join(str(t) for t in row) + "},\n")
        lines.append("    },\n")
    if not tabled:
        lines.append("    {},\n")
    lines.append("};\n")
    row_of = {bid: i + 1 for i, bid in enumerate(tabled)}

    # **The block a block is built from** -- a staircase's planks. 0 for all
    # the rest, which is air and so never a block anything turns into.
    for bid, entry in blocks.items():
        if "model" in entry and entry["model"] not in blocks:
            sys.exit(f"configure: block {bid}'s model {entry['model']} is not a block")

    def byte_table(name, ctype, value) -> None:
        lines.append(f"inline constexpr {ctype} {name}[kBlockTableSize] = {{\n")
        for start in range(0, table_size, 16):
            row = (str(value(bid)) for bid in range(start, start + 16))
            lines.append("    " + ", ".join(row) + ",\n")
        lines.append("};\n")

    lines.append("\n")
    byte_table("kMetadataFaceRow", "mc::u8", lambda bid: row_of.get(bid, 0))
    lines.append("\n// `model`: the block a staircase turns into with something solid on it.\n")
    byte_table("kModelBlock", "mc::block::BlockId",
               lambda bid: blocks.get(bid, {}).get("model", 0))

    lines.append("\n}  // namespace mcver\n")

    (out / "blocks.hpp").write_text("".join(lines))
    return True


def write_items(out: Path, m: dict) -> bool:
    """Turn data/<version>/items.json into a constexpr table.

    Same shape as write_blocks and for the same reasons, with one difference:
    the table stops at 512 rather than covering every id the format allows. Item
    ids are shorts and a1.1.2's two music discs are 2256 and 2257, so a table
    indexed by id over the whole range would be 2,258 rows to carry two that
    cannot be obtained, placed or used. Ids past the end come back as the
    unknown item; core/item/registry.hpp says what that costs and what it does
    not.
    """
    source = REPO / m["data"] / "items.json"
    if not source.is_file():
        (out / "items.hpp").write_text(
            BANNER.format(id=m["id"]) + "#pragma once\n"
            "// No items.json for this version yet.\n")
        return False

    doc = json.loads(source.read_text())
    items = {entry["id"]: entry for entry in doc["items"]}

    table_size = 512
    outside = sorted(i for i in items if i >= table_size)

    # Two items can share a name -- the door you carry is 324 and the door block
    # is 64, and both are called wooden_door, which is the point. The block form
    # takes a "Block" suffix so the generated enum still has one name per id.
    name_counts = {}
    for entry in items.values():
        name_counts[entry["name"]] = name_counts.get(entry["name"], 0) + 1

    def enum_name(entry) -> str:
        base = pascal(entry["name"])
        if name_counts[entry["name"]] > 1 and entry["id"] < 256:
            return base + "Block"
        return base

    def definition(entry) -> str:
        if entry is None:
            # **The unknown row hits for 1**, which is not a filler value: it is
            # what `InventoryPlayer.getDamageVsEntity` answers for an empty
            # slot, so a caller can read the column for the bare hand as well.
            # See core/item/item_def.hpp.
            return ('{"unknown", 0, 0, 0, 1, 1, IconSheet::Items, '
                    'ItemDef::kNotArmour, ItemDef::kNotABucket, '
                    'SpawnsEntity::None, 0, false, false, false, false}')
        return (
            f'{{"{entry["name"]}", {entry["icon"]}, {entry["places"]}, '
            f'{entry["durability"]}, {entry["damageVsEntity"]}, {entry["stack"]}, '
            f'IconSheet::{"Terrain" if entry["sheet"] == "terrain" else "Items"}, '
            f'{entry["armour"]}, {entry["bucket"]}, '
            f'SpawnsEntity::{pascal(entry["spawns"])}, {entry["spawnVariant"]}, '
            f'{c_bool(bool(entry["fx"]))}, {c_bool(entry["tills"])}, '
            f'{c_bool(entry["palette"])}, true}}'
        )

    in_table = sorted(i for i in items if i < table_size)
    # **The palette is over every row, not only the ones the array reaches.**
    # a1.1.2's ids run 0..346 and then jump to 2256 for the two music discs, so
    # a contiguous table that covered them would be 2,258 entries to carry two.
    # They get a side table instead (`kOutsideItems` below) and they are in the
    # palette like anything else -- a skeleton killing a creeper drops one, so
    # they are obtainable and a catalogue that omitted them would have a hole.
    palette = [i for i in sorted(items) if items[i]["palette"]]

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/item/item_def.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::item::IconSheet;\n",
        "using mc::item::SpawnsEntity;\n",
        "using mc::item::ItemDef;\n",
        "\n// Named ids, so no literal item number appears anywhere else.\n",
        "enum class Item : mc::item::ItemId {\n",
    ]
    for iid in sorted(items):
        lines.append(f"    {enum_name(items[iid])} = {iid},\n")
    lines.append("};\n")

    lines.append(f"\ninline constexpr int kItemTableSize = {table_size};\n")
    lines.append(f"inline constexpr int kItemCount = {len(items)};\n")
    lines.append("\n// Ids this version defines that the contiguous table does "
                 "not reach --\n// a1.1.2's two music discs at 2256 and 2257, "
                 "which are 1,910 ids past the\n// end of the item run. They "
                 "are held as a pair of parallel arrays rather\n// than as "
                 "1,910 blank rows; `item::def` falls back to a scan over them, "
                 "which\n// costs nothing for an id the table does reach. "
                 "See core/item/registry.hpp.\n")
    lines.append(f"inline constexpr int kItemsOutsideTable = {len(outside)};\n")
    lines.append("\ninline constexpr ItemDef kUnknownItem =\n    "
                 + definition(None) + ";\n")
    lines.append("\ninline constexpr ItemDef kItems[kItemTableSize] = {\n")
    for iid in range(table_size):
        entry = items.get(iid)
        label = entry["name"] if entry else "unknown"
        lines.append(f"    /* {iid:3} {label:<22} */ {definition(entry)},\n")
    lines.append("};\n")

    if outside:
        lines.append("\ninline constexpr mc::item::ItemId "
                     "kOutsideItemIds[kItemsOutsideTable] = {\n    "
                     + ", ".join(str(i) for i in outside) + ",\n};\n")
        lines.append("\ninline constexpr ItemDef "
                     "kOutsideItems[kItemsOutsideTable] = {\n")
        for iid in outside:
            lines.append(f"    /* {iid} {items[iid]['name']:<12} */ "
                         f"{definition(items[iid])},\n")
        lines.append("};\n")
    else:
        # An empty array is not valid C++, and a version with no such ids is
        # the ordinary case rather than an error.
        lines.append("\ninline constexpr mc::item::ItemId* kOutsideItemIds = nullptr;\n")
        lines.append("inline constexpr ItemDef* kOutsideItems = nullptr;\n")

    lines.append("\n// The Creative hand's offering, in id order, as a table "
                 "rather than a scan.\n// Which items are in it is decided by "
                 "tools/genref.java, not here.\n")
    lines.append(f"inline constexpr int kPaletteSize = {len(palette)};\n")
    lines.append("inline constexpr mc::item::ItemId kPalette[kPaletteSize] = {\n")
    for start in range(0, len(palette), 12):
        row = ", ".join(str(i) for i in palette[start:start + 12])
        lines.append(f"    {row},\n")
    lines.append("};\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "items.hpp").write_text("".join(lines))
    return True


def write_drops(out: Path, m: dict) -> bool:
    """Emit what each block leaves behind when it is removed.

    Six numbers a block, generated in turn (tools/genref.java --drops), so no
    value here was typed by a human and none of them is a guess about a method
    that takes a Random. The per-metadata rows are held apart from the main
    table because only three blocks in a1.1.2 have one -- a door, an iron door
    and a crop -- and giving all 256 rows sixteen entries would be 8 KB of
    .rodata to carry three.
    """
    source = REPO / m["data"] / "drops.json"
    if not source.is_file():
        return False

    doc = json.loads(source.read_text())
    rows = {entry["id"]: entry for entry in doc["drops"]}
    size = m["constants"].get("blockTableSize", 256)

    # The side table, in the order the blocks that need one appear.
    meta_rows = []
    meta_index = {}
    for bid in sorted(rows):
        entry = rows[bid]
        if "itemByMetadata" in entry:
            meta_index[bid] = len(meta_rows)
            meta_rows.append(entry["itemByMetadata"])

    def definition(entry) -> str:
        if entry is None:
            return "{0, 0, 0, 0, 0, 0, -1}"
        return (
            f'{{{entry["item"]}, {entry.get("altItem", 0)}, {entry.get("altOneIn", 0)}, '
            f'{entry.get("countMin", 0)}, {entry.get("countSpread", 0)}, '
            f'{entry.get("countOneIn", 0)}, {meta_index.get(entry["id"], -1)}}}'
        )

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/util/types.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::i8;\n",
        "using mc::u8;\n",
        "using mc::u16;\n",
        "\n// One block's drop rule. See data/<version>/drops.json for what each field\n"
        "// means and core/tick/drop.hpp for the four lines that run them.\n",
        "struct BlockDrop {\n",
        "    u16 item;         // the usual answer; 0 is 'nothing'\n",
        "    u16 altItem;      // the other answer, when altOneIn is not 0\n",
        "    u8 altOneIn;      // nextInt(altOneIn) == 0 picks altItem\n",
        "    u8 countMin;      // how many, before the roll below\n",
        "    u8 countSpread;   // + nextInt(countSpread), when not 0\n",
        "    u8 countOneIn;    // nextInt(countOneIn) == 0 ? countMin : 0, when not 0\n",
        "    i8 metadataRow;   // index into kDropByMetadata, or -1\n",
        "};\n",
        f"\ninline constexpr int kDropTableSize = {size};\n",
    ]
    lines.append(f"inline constexpr int kDropMetadataRows = {max(len(meta_rows), 1)};\n")
    lines.append(
        "\n// [row][metadata] -> the item that metadata drops. Only a door and a crop\n"
        "// need one; a block with metadataRow -1 answers with `item` whatever its\n"
        "// metadata is.\n"
    )
    lines.append("inline constexpr u16 kDropByMetadata[kDropMetadataRows][16] = {\n")
    if meta_rows:
        for bid in sorted(meta_index, key=lambda b: meta_index[b]):
            row = rows[bid]["itemByMetadata"]
            lines.append("    {" + ", ".join(str(v) for v in row)
                         + f"}},   // {rows[bid].get('name', bid)}\n")
    else:
        lines.append("    {0},\n")
    lines.append("};\n")

    lines.append("\ninline constexpr BlockDrop kBlockDrops[kDropTableSize] = {\n")
    for bid in range(size):
        entry = rows.get(bid)
        label = entry.get("name", "") if entry else ""
        lines.append(f"    /* {bid:3} {label:<22} */ {definition(entry)},\n")
    lines.append("};\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "drops.hpp").write_text("".join(lines))
    return True


def write_paintings(out: Path, m: dict) -> bool:
    """Emit the art table -- what pictures exist and where they live in kz.png.

    `er` (EnumArt) is twenty-four rows of five values and every one of them is a
    literal in one static initialiser, so this could have been typed. It is
    generated for the same reason the drop table is: a name in this table is
    what a painting's NBT stores, and a name that was remembered rather than
    read is a save file that does not round-trip.
    """
    source = REPO / m["data"] / "paintings.json"
    if not source.is_file():
        return False

    doc = json.loads(source.read_text())
    arts = doc["paintings"]

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/entity/painting_art.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::entity::PaintingArt;\n",
        f"\ninline constexpr int kPaintingCount = {len(arts)};\n",
        "\ninline constexpr PaintingArt kPaintings[kPaintingCount] = {\n",
    ]
    for art in arts:
        lines.append(
            f'    {{"{art["name"]}", {art["width"]}, {art["height"]}, '
            f'{art["u"]}, {art["v"]}}},\n'
        )
    lines.append("};\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "paintings.hpp").write_text("".join(lines))
    return True


def write_selection(out: Path, m: dict) -> bool:
    """Emit the selection shapes -- what a ray tests against, per block and metadata.

    Two tables rather than one box per (id, metadata) pair: 1,120 pairs hold
    only 40 distinct boxes, so the index is a byte and the whole thing is about
    5 KB instead of 53 KB. On a console with 40 MB of heap that difference is
    worth the indirection.

    The source is generated in turn -- see tools/gen_selection.py -- so no
    number here was ever typed by a human.
    """
    source = REPO / m["data"] / "selection.json"
    if not source.is_file():
        return False

    doc = json.loads(source.read_text())
    shapes = doc["shapes"]
    index = {int(k): v for k, v in doc["index"].items()}

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/util/types.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::u8;\n",
        "\n// The shape a ray is tested against, which is **not** the collision shape:\n",
        "// a torch has no collision box at all and still has one of these. Floats,\n",
        "// because every bound in the jar came from setBlockBounds, which takes floats.\n",
        f"\ninline constexpr int kSelectionShapeCount = {len(shapes)};\n",
        "\ninline constexpr float kSelectionShapes[kSelectionShapeCount][6] = {\n",
    ]
    for i, box in enumerate(shapes):
        values = ", ".join(f"{v!r}f" for v in box)
        lines.append(f"    {{{values}}},   // {i}\n")
    lines.append("};\n")

    lines.append(
        "\n// [block id][metadata] -> an index into kSelectionShapes. Index 0 is the\n"
        "// unit cube, so a block this version never constructs reads as a full block\n"
        "// rather than as something a ray falls through.\n"
    )
    unit = shapes.index([0.0, 0.0, 0.0, 1.0, 1.0, 1.0])
    if unit != 0:
        sys.exit("configure: selection shape 0 is not the unit cube; the fallback assumes it is")
    size = m["constants"].get("blockTableSize", 256)
    lines.append(f"\ninline constexpr int kSelectionIndexSize = {size};\n")
    lines.append(f"\ninline constexpr u8 kSelectionIndex[kSelectionIndexSize][16] = {{\n")
    for bid in range(size):
        row = index.get(bid, [0] * 16)
        lines.append("    {" + ", ".join(str(v) for v in row) + "},\n")
    lines.append("};\n")

    # **One box per block and not per metadata**, because the thing that draws
    # it has no metadata to read: `RenderBlocks.renderBlockAsItem` calls
    # `Block.setBlockBoundsForItemRender` on the singleton and draws what that
    # leaves. It is the same shape list, so the two columns share their storage.
    item_render = {int(k): v for k, v in doc.get("itemRender", {}).items()}
    lines.append(
        "\n// [block id] -> the shape an item render draws, an index into kSelectionShapes.\n"
        "// `Block.setBlockBoundsForItemRender`, which the hand, the inventory slot and a\n"
        "// dropped stack all go through and which no metadata reaches. Empty on Block, so\n"
        "// this is the constructor's bounds for all but the button and the two pressure\n"
        "// plates -- the blocks whose world shape lives in setBlockBoundsBasedOnState and\n"
        "// is therefore a leftover at metadata 0.\n"
    )
    lines.append("\ninline constexpr u8 kItemRenderIndex[kSelectionIndexSize] = {\n")
    for row in range(0, size, 8):
        values = ", ".join(str(item_render.get(bid, 0)) for bid in range(row, min(row + 8, size)))
        lines.append(f"    {values},\n")
    lines.append("};\n")

    lines.append("\n}  // namespace mcver\n")

    (out / "selection.hpp").write_text("".join(lines))
    return True


def write_placement(out: Path, m: dict) -> bool:
    """Emit which metadata a block lands with, per face struck.

    `Block.onBlockPlaced`, which is what makes a torch on a wall a wall torch.
    Six of the seventy blocks answer differently per face; the rest are zero,
    and a table is still the right shape for it because the alternative is a
    switch full of block ids. (A furnace and a staircase turn from their
    neighbours in onBlockAdded, which is a tick behaviour, not this table.)

    Generated in turn from a real jar -- see tools/gen_selection.py.
    """
    source = REPO / m["data"] / "placement.json"
    if not source.is_file():
        return False

    doc = json.loads(source.read_text())
    table = {int(k): v for k, v in doc["metadata"].items()}
    size = m["constants"].get("blockTableSize", 256)

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/util/types.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::u8;\n",
        "\n// [block id][face] -> the metadata a placement leaves, in mc::mesh::Face order\n"
        "// (0 -Y, 1 +Y, 2 -Z, 3 +Z, 4 -X, 5 +X). Zero for everything that does not care,\n"
        "// which is most of the table.\n",
        f"\ninline constexpr int kPlacementTableSize = {size};\n",
        "\ninline constexpr u8 kPlacementMetadata[kPlacementTableSize][6] = {\n",
    ]
    for bid in range(size):
        row = table.get(bid, [0] * 6)
        lines.append("    {" + ", ".join(str(v) for v in row) + "},\n")
    lines.append("};\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "placement.hpp").write_text("".join(lines))
    return True


def write_harvest(out: Path, m: dict) -> bool:
    """Emit what Survival asks of a block and a held item.

    Which blocks a bare hand cannot harvest, how fast each tool digs what it
    digs, which blocks each tool may harvest, what a hit and a break wear off
    it, how much an armour piece absorbs and how much a food heals. All of it
    asked of a running jar by tools/genref.java --harvest, so nothing here is a
    number anybody typed.

    The tool rows are sparse -- a tool's own efficiency list and harvest list
    sit in two flat side arrays and the row holds where its run starts -- because
    the alternative is a [item][block] matrix of 1.0 with twenty-one rows that
    say anything.
    """
    source = REPO / m["data"] / "harvest.json"
    if not source.is_file():
        return False

    doc = json.loads(source.read_text())
    size = m["constants"].get("blockTableSize", 256)
    gated = {entry["id"] for entry in doc["needsTool"]}

    efficiency = []
    harvests = []
    tool_rows = []
    for tool in doc["tools"]:
        tool_rows.append(
            f'    {{{tool["id"]}, {tool["wearOnHit"]}, {tool["wearOnBreak"]}, '
            f'{len(efficiency)}, {len(tool["efficiency"])}, '
            f'{len(harvests)}, {len(tool["harvests"])}}},   // {tool["name"]}\n')
        efficiency.extend(tool["efficiency"])
        harvests.extend(tool["harvests"])

    def c_float(value: float) -> str:
        text = repr(float(value))
        return text + "f"

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/util/types.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::i16;\n",
        "using mc::u8;\n",
        "using mc::u16;\n",
        "\n// [block id] -> true when an empty hand cannot harvest it. `dm.b(Lly;)Z` is\n"
        "// true outright unless the block's material is one of four, and this is\n"
        "// that set as the jar answered it. See data/<version>/harvest.json.\n",
        f"\ninline constexpr int kHarvestBlockTableSize = {size};\n",
        "\ninline constexpr bool kBlockNeedsTool[kHarvestBlockTableSize] = {\n",
    ]
    for bid in range(size):
        lines.append(f"    {c_bool(bid in gated)},\n")
    lines.append("};\n")

    lines.append(
        "\n// One block a tool digs at other than 1.0, from `di.a(Lev;Lly;)F`.\n"
        "struct ToolEfficiency {\n"
        "    u16 block;\n"
        "    float value;\n"
        "};\n"
        "\n// One item that answers something other than Item's defaults. The runs\n"
        "// index kToolEfficiencies and kToolHarvests.\n"
        "struct ToolRule {\n"
        "    i16 item;\n"
        "    u8 wearOnHit;       // what hitEntity adds to the stack's damage\n"
        "    u8 wearOnBreak;     // what hitBlock adds\n"
        "    u16 efficiencyFirst;\n"
        "    u8 efficiencyCount;\n"
        "    u16 harvestFirst;\n"
        "    u8 harvestCount;\n"
        "};\n"
    )
    lines.append(f"\ninline constexpr int kToolEfficiencyCount = {max(len(efficiency), 1)};\n")
    lines.append("inline constexpr ToolEfficiency kToolEfficiencies[kToolEfficiencyCount] = {\n")
    for block, value in efficiency or [[0, 1.0]]:
        lines.append(f"    {{{block}, {c_float(value)}}},\n")
    lines.append("};\n")
    lines.append(f"\ninline constexpr int kToolHarvestCount = {max(len(harvests), 1)};\n")
    lines.append("inline constexpr u16 kToolHarvests[kToolHarvestCount] = {\n")
    for block in harvests or [0]:
        lines.append(f"    {block},\n")
    lines.append("};\n")
    lines.append(f"\ninline constexpr int kToolRuleCount = {max(len(tool_rows), 1)};\n")
    lines.append("inline constexpr ToolRule kToolRules[kToolRuleCount] = {\n")
    lines.extend(tool_rows or ["    {-1, 0, 0, 0, 0, 0, 0},\n"])
    lines.append("};\n")

    lines.append(
        "\n// `mr.aY` -- what one armour piece contributes to `eu.f()`.\n"
        "struct ArmourRule {\n"
        "    i16 item;\n"
        "    u8 points;\n"
        "};\n"
    )
    lines.append(f"\ninline constexpr int kArmourRuleCount = {max(len(doc['armour']), 1)};\n")
    lines.append("inline constexpr ArmourRule kArmourRules[kArmourRuleCount] = {\n")
    for entry in doc["armour"] or [{"id": -1, "points": 0, "name": "none"}]:
        lines.append(f'    {{{entry["id"]}, {entry["points"]}}},   // {entry["name"]}\n')
    lines.append("};\n")

    lines.append(
        "\n// `oj.a` -- the health ItemFood hands to `ge.b(I)V`.\n"
        "struct FoodRule {\n"
        "    i16 item;\n"
        "    u8 heals;\n"
        "};\n"
    )
    lines.append(f"\ninline constexpr int kFoodRuleCount = {max(len(doc['food']), 1)};\n")
    lines.append("inline constexpr FoodRule kFoodRules[kFoodRuleCount] = {\n")
    for entry in doc["food"] or [{"id": -1, "heals": 0, "name": "none"}]:
        lines.append(f'    {{{entry["id"]}, {entry["heals"]}}},   // {entry["name"]}\n')
    lines.append("};\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "harvest.hpp").write_text("".join(lines))
    return True


def write_recipes(out: Path, m: dict) -> bool:
    """Emit crafting, smelting and fuel, as the jar holds them.

    `crafting` keeps CraftingManager's own order, because the first recipe that
    matches wins and the order is part of the rule. Cells are padded to nine with
    -1 so every row is the same size; only `width * height` of them are read.
    """
    source = REPO / m["data"] / "recipes.json"
    if not source.is_file():
        return False

    doc = json.loads(source.read_text())

    lines = [
        BANNER.format(id=m["id"]),
        "#pragma once\n",
        '\n#include "core/util/types.hpp"\n',
        "\nnamespace mcver {\n",
        "\nusing mc::i16;\n",
        "using mc::u8;\n",
        "using mc::u16;\n",
        "\n// `bv` -- one shaped recipe. `cells` are item ids row by row, -1 for a blank;\n"
        "// only the first width * height are meaningful.\n",
        "struct CraftingRecipe {\n",
        "    u8 width;\n",
        "    u8 height;\n",
        "    i16 cells[9];\n",
        "    i16 result;\n",
        "    u8 count;\n",
        "    i16 damage;\n",
        "};\n",
    ]
    recipes = doc["crafting"]
    lines.append(f"\ninline constexpr int kCraftingRecipeCount = {max(len(recipes), 1)};\n")
    lines.append("inline constexpr CraftingRecipe kCraftingRecipes[kCraftingRecipeCount] = {\n")
    for r in recipes or [{"width": 0, "height": 0, "cells": [], "result": -1, "count": 0,
                          "damage": 0, "name": "none"}]:
        cells = list(r["cells"]) + [-1] * (9 - len(r["cells"]))
        lines.append(
            f'    {{{r["width"]}, {r["height"]}, {{{", ".join(str(c) for c in cells)}}}, '
            f'{r["result"]}, {r["count"]}, {r["damage"]}}},   // {r["name"]}\n')
    lines.append("};\n")

    lines.append(
        "\n// TileEntityFurnace's result for one input id.\n"
        "struct SmeltingRule {\n"
        "    i16 input;\n"
        "    i16 result;\n"
        "};\n"
    )
    smelting = doc["smelting"]
    lines.append(f"\ninline constexpr int kSmeltingRuleCount = {max(len(smelting), 1)};\n")
    lines.append("inline constexpr SmeltingRule kSmeltingRules[kSmeltingRuleCount] = {\n")
    for s in smelting or [{"input": -1, "result": -1, "name": "none"}]:
        lines.append(f'    {{{s["input"]}, {s["result"]}}},   // {s["name"]}\n')
    lines.append("};\n")

    lines.append(
        "\n// TileEntityFurnace's burn time, in ticks, for one item.\n"
        "struct FuelRule {\n"
        "    i16 item;\n"
        "    u16 ticks;\n"
        "};\n"
    )
    fuel = doc["fuel"]
    lines.append(f"\ninline constexpr int kFuelRuleCount = {max(len(fuel), 1)};\n")
    lines.append("inline constexpr FuelRule kFuelRules[kFuelRuleCount] = {\n")
    for f in fuel or [{"id": -1, "ticks": 0, "name": "none"}]:
        lines.append(f'    {{{f["id"]}, {f["ticks"]}}},   // {f["name"]}\n')
    lines.append("};\n")
    lines.append("\n}  // namespace mcver\n")

    (out / "recipes.hpp").write_text("".join(lines))
    return True


def write_rsf(out: Path, m: dict) -> None:
    template = REPO / "packaging" / "3dalpha.rsf.in"
    if not template.is_file():
        return
    pkg = m["packaging"]
    text = (
        template.read_text()
        .replace("@APP_TITLE@", m["appTitle"])
        .replace("@PRODUCT_CODE@", pkg["productCode"])
        .replace("@UNIQUE_ID@", pkg["uniqueId"])
    )
    (out / f"{m['id']}.rsf").write_text(text)


def main() -> None:
    if len(sys.argv) != 3:
        sys.exit(__doc__)

    version_id, out_dir = sys.argv[1], Path(sys.argv[2])
    out_dir.mkdir(parents=True, exist_ok=True)

    m = load_manifest(version_id)
    write_version_config(out_dir, m)
    unfilled = write_version_slots(out_dir, m)
    write_cmake(out_dir, m)
    write_rsf(out_dir, m)
    has_blocks = write_blocks(out_dir, m)
    has_items = write_items(out_dir, m)
    has_drops = write_drops(out_dir, m)
    has_paintings = write_paintings(out_dir, m)
    has_selection = write_selection(out_dir, m)
    has_placement = write_placement(out_dir, m)
    has_harvest = write_harvest(out_dir, m)
    has_recipes = write_recipes(out_dir, m)

    print(f"configure: {m['display']} (protocol {m['constants']['protocol']}) -> {out_dir}")
    if not has_blocks:
        print(f"configure: no {m['data']}/blocks.json yet")
    if not has_items:
        print(f"configure: no {m['data']}/items.json yet -- "
              "run tools/genref.java --items")
    if not has_drops:
        print(f"configure: no {m['data']}/drops.json yet -- "
              "run tools/genref.java --drops")
    if not has_paintings:
        print(f"configure: no {m['data']}/paintings.json yet -- "
              "run tools/genref.java --art")
    if not has_selection:
        print(f"configure: no {m['data']}/selection.json yet -- run tools/gen_selection.py")
    if not has_placement:
        print(f"configure: no {m['data']}/placement.json yet -- run tools/gen_selection.py")
    if not has_harvest:
        print(f"configure: no {m['data']}/harvest.json yet -- "
              "run tools/genref.java --harvest")
    if not has_recipes:
        print(f"configure: no {m['data']}/recipes.json yet -- "
              "run tools/genref.java --recipes")
    if unfilled:
        print(f"configure: slots not implemented yet: {', '.join(unfilled)}")


if __name__ == "__main__":
    main()
