#!/usr/bin/env python3
"""Regenerate docs/code-map.md and docs/doc-index.md.

Both files exist so that a reader -- human or agent -- can find the one file or
the one section that answers a question without opening everything. They are
generated rather than written because a hand-kept index rots silently, and a
rotted index is worse than none: it sends you to the wrong line with confidence.

  python3 tools/gen_index.py          rewrite both
  python3 tools/gen_index.py --check  exit 1 if either is stale (for CI)

The code map's one-liners come from the first sentence of each file's header
comment, which is the project's existing convention -- every header opens with
one. Keeping that sentence a real summary is what keeps the map useful.
"""

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Directory -> what the subsystem is for. The map groups by directory, and a
# bare path is not self-explanatory to someone who has not read the tree.
GROUPS = {
    "src/core/block": "Block table and registry",
    "src/core/entity": "Entities",
    "src/core/gui": "GUI primitives shared by the menu and the HUD",
    "src/core/io": "Filesystem abstraction",
    "src/core/item": "Item stacks",
    "src/core/map": "The bottom-screen map",
    "src/core/mesh": "Section -> quads",
    "src/core/nbt": "NBT reader, writer and tag preservation",
    "src/core/net": "Protocol 2 networking",
    "src/core/render": "What is loaded, meshed and drawn around the camera",
    "src/core/settings": "INI settings, console-wide and per-world",
    "src/core/texture": "Texture packs, atlases, PNG and zip",
    "src/core/util": "Small shared utilities",
    "src/core/world": "Chunks, sections, lighting, storage",
    "src/core/world/format": "The Packed container format",
    "src/impl/entitydata": "Version slot: entity data",
    "src/impl/storage": "Version slot: on-disk world format",
    "src/impl/strings": "Version slot: strings",
    "src/impl/worldgen": "Version slot: world generation",
    "src/platform/ctr": "3DS: GPU, screens, menus, HUD",
    "src/platform/host": "Linux/SDL2 harness",
    "tests": "Host test suite",
}


def header_summary(path):
    """First sentence of the file's leading // comment block."""
    out = []
    started = False
    with open(path, encoding="utf-8", errors="replace") as fh:
        for line in fh:
            s = line.strip()
            if s.startswith("//"):
                started = True
                out.append(s[2:].strip())
            elif started:
                break
            elif s and not s.startswith("#pragma"):
                break
    text = " ".join(out).strip()
    if not text:
        return ""
    # First sentence, keeping abbreviations like "a1.1.2" intact by requiring
    # the period to be followed by a space and a capital or end of string.
    m = re.search(r"\.(?:\s+(?=[A-Z*`])|$)", text)
    if m:
        text = text[: m.start() + 1]
    text = re.sub(r"\s+", " ", text)
    return text.replace("|", "\\|")


def loc(path):
    with open(path, "rb") as fh:
        return sum(1 for _ in fh)


def build_code_map():
    modules = {}  # group -> list of (name, summary, lines, files)
    for dirpath, dirnames, filenames in os.walk(os.path.join(ROOT, "src")):
        dirnames.sort()
        rel = os.path.relpath(dirpath, ROOT)
        for fn in sorted(filenames):
            if not fn.endswith((".hpp", ".cpp", ".h", ".c")):
                continue
            stem, ext = os.path.splitext(fn)
            if ext in (".cpp", ".c") and os.path.exists(
                os.path.join(dirpath, stem + ".hpp")
            ):
                continue  # counted with its header
            full = os.path.join(dirpath, fn)
            lines = loc(full)
            sib = os.path.join(dirpath, stem + ".cpp")
            files = fn
            if ext == ".hpp" and os.path.exists(sib):
                lines += loc(sib)
                files = stem + ".{hpp,cpp}"
            summary = header_summary(full)
            group = rel
            # Fold slot implementations up to their slot directory.
            for g in GROUPS:
                if rel.startswith(g + "/") and g.startswith("src/impl"):
                    group = g
            modules.setdefault(group, []).append((files, summary, lines, rel))

    total = sum(m[2] for v in modules.values() for m in v)
    lines = [
        "# Code map",
        "",
        "*Generated by `tools/gen_index.py` -- do not edit by hand. Re-run it after adding,",
        "removing or renaming a file.*",
        "",
        "One row per module. `foo.{hpp,cpp}` is a header and its implementation counted",
        "together. The summary is the first sentence of the file's header comment, so if a",
        "row here is unhelpful, the fix is in that comment. Line counts say where the",
        "weight is, not what is important.",
        "",
        f"**{len(modules)} directories, "
        f"{sum(len(v) for v in modules.values())} modules, {total:,} lines.**",
        "",
    ]
    for group in sorted(modules):
        blurb = GROUPS.get(group, "")
        lines.append(f"## `{group}/`" + (f" -- {blurb}" if blurb else ""))
        lines.append("")
        lines.append("| Module | Lines | What it is |")
        lines.append("|---|--:|---|")
        for files, summary, n, rel in sorted(modules[group]):
            path = files if rel == group else f"{os.path.relpath(rel, group)}/{files}"
            lines.append(f"| `{path}` | {n} | {summary} |")
        lines.append("")
    return "\n".join(lines)


def build_doc_index():
    docs = sorted(
        f for f in os.listdir(os.path.join(ROOT, "docs")) if f.endswith(".md")
    )
    docs = [d for d in docs if d not in ("doc-index.md", "code-map.md")]

    lines = [
        "# Documentation index",
        "",
        "*Generated by `tools/gen_index.py` -- do not edit by hand. Re-run it after editing",
        "any heading in `docs/`.*",
        "",
        "Every section of every document, with the line range it occupies. The point is to",
        "read a section rather than a file: `docs/status.md` alone is over 50,000 tokens, and",
        "almost every question it answers lives in one of its sections.",
        "",
        "```sh",
        "sed -n '646,700p' docs/status.md      # read one section",
        "grep -n 'geometry shader' docs/*.md   # find which section first",
        "```",
        "",
    ]
    for doc in docs:
        path = os.path.join(ROOT, "docs", doc)
        with open(path, encoding="utf-8", errors="replace") as fh:
            content = fh.read().split("\n")
        n = len(content)
        heads = []
        fenced = False
        for i, line in enumerate(content, 1):
            if line.startswith("```"):
                fenced = not fenced
            if fenced:
                continue
            m = re.match(r"^(#{1,4}) +(.*)", line)
            if m:
                heads.append((len(m.group(1)), m.group(2).strip(), i))
        size = os.path.getsize(path)
        lines.append(f"## `docs/{doc}`")
        lines.append("")
        lines.append(f"{n:,} lines, ~{size // 4:,} tokens.")
        lines.append("")
        for idx, (depth, title, start) in enumerate(heads):
            if depth == 1:
                continue
            end = heads[idx + 1][2] - 1 if idx + 1 < len(heads) else n
            indent = "  " * (depth - 2)
            title = title.replace("`", "`")
            lines.append(f"{indent}- **{start}-{end}** {title}")
        lines.append("")
    return "\n".join(lines)


def write(path, text, check):
    full = os.path.join(ROOT, path)
    old = ""
    if os.path.exists(full):
        with open(full, encoding="utf-8") as fh:
            old = fh.read()
    if old == text:
        return True
    if check:
        print(f"stale: {path}", file=sys.stderr)
        return False
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {path}")
    return True


def main():
    check = "--check" in sys.argv
    ok = write("docs/code-map.md", build_code_map() + "\n", check)
    ok &= write("docs/doc-index.md", build_doc_index() + "\n", check)
    if check and not ok:
        print("run: python3 tools/gen_index.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
